### ISSUE TITLE
Missing Transactions when Navigating back to the Home Activity

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-java#3140] opened 2024-01-15 16:01 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

unknown

### Proguard

Enabled

### Version

6.33.1 and 7.0.0-rc.2

### Steps to Reproduce

Activity A starts - transaction A starts
Activity B starts - transaction B starts, transaction A finishes
Activity B finishes transaction B finishes
Activity A resumes, but there is no active transaction until new activity starts
Using manual setup with SentryAndroid.init exact configuration in :thread:

Contact me for the 42-second video the user recorded which demonstrates the problem

### Expected Result

new transaction for the home activity should start, even though the activity was loaded earlier.

### Actual Result

no new transaction is started.

Do we need their code showing how their Activity is defined?
Maybe they're not re-loading the activity and our SDK is trying to listen/hook into some kind of Activity-Loading function?

**Comment by romtsn** [comment] 2024-01-17 13:52
This is intended behavior as there's no screen load when going back to the existing Activity from the backstack. We don't provide auto-instrumentation for that, but the customer can still start a custom transaction if they want to. 

This will also be solved by only-spans as it requires no active transaction.

Closing this for now.

**Closed by romtsn** 2024-01-17 13:52 UTC
Labels: Type: Bug, Platform: Android, Platform: Java, Waiting for: Product Owner
