### ISSUE TITLE
Memory issues with breadcrumbs

### ISSUE THREAD

**Issue by antonanymind** [getsentry/sentry-java#1851] opened 2021-12-17 07:55 UTC
I have OOM issues with new versions of Sentry in my Kotlin(Spring Boot) project after I've migrated from the legacy SDK. According to MAT, I have a lot of breadcrumb objects in the heap.

```
Class Name          |   Objects | Shallow Heap |  Retained Heap
----------------------------------------------------------------
io.sentry.Breadcrumb| 1,711,441 |   68,457,640 | >= 451,814,880
----------------------------------------------------------------
```
80% of objects in the heap are breadcrumbs for some reason. The growth continues until the app dies with code 137.

This is my Sentry configuration.

Gradle:
```
    implementation 'io.sentry:sentry-spring-boot-starter:5.1.0'
    implementation 'io.sentry:sentry-logback:5.1.0'
```
Logback.xml:
```
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>
    <appender name="Sentry" class="io.sentry.logback.SentryAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>WARN</level>
        </filter>
    </appender>

    <root level="info">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="Sentry" />
    </root>
</configuration>
```
I don't know what to do. Do you guys have any suggestions?

**Comment by maciejwalkowiak** [comment] 2021-12-17 09:28
By default, scope can store up to 100 breadcrumbs. Did you change the value for `sentry.max-breadcrumbs` property?

If its 100, this would mean that there are 17000 scopes living simultaneously.

Can you share a bit more about your application that could be helpful to debug? It it only Spring MVC, or do you use more instrumentations?

**Comment by antonanymind** [comment] 2021-12-17 10:12
>Did you change the value for sentry.max-breadcrumbs property?
No. The only property I didn't share was the DSN.
>Is it only Spring MVC, or do you use more instrumentations?
It's WebFlux, but with the threading model from Tomcat.
This is how it looks:

```
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-tomcat' 
```
The reason is almost the same as described here https://stackoverflow.com/questions/43472091/using-spring-boot-weblfux-with-embedded-tomcat.
We also use Google PubSub:
```
    implementation 'org.springframework.cloud:spring-cloud-gcp-starter-pubsub:1.2.6.RELEASE'
    implementation 'org.springframework.integration:spring-integration-core'
```

**Comment by antonanymind** [comment] 2021-12-17 10:21
I can actually filter out all breadcrumbs. We don't really use this feature much. I had an idea to turn them off temporarily like this:
```
Sentry.init { options ->
  options.beforeBreadcrumb = BeforeBreadcrumbCallback { breadcrumb, hint ->
      null 
  }
}
```
May it potentially help?

**Comment by marandaneto** [comment] 2021-12-17 10:33
> 

yes, or set `options .maxBreadcrumbs = 0`, so breadcrumbs don't even get added to the list

**Comment by maciejwalkowiak** [comment] 2021-12-17 10:33
Yes, as a workaround it should help - as breadcrumbs wont be ever added to a scope. I'll try to reproduce your issue locally as collecting breadcrumbs endlessly should never happen.

**Comment by antonanymind** [comment] 2021-12-17 10:51
Ok cool. Thank you, guys. Should you need more information on that, pls let me know. I can even show you the breadcrumbs.

**Comment by maciejwalkowiak** [comment] 2021-12-19 18:36
Most likely, the error come from our [buggy](https://github.com/getsentry/sentry-java/issues/1790) Webflux integration. Until its fixed I recommend:

- disable `SentryWebfluxAutoConfiguration`:

```java
@SpringBootApplication(exclude = SentryWebfluxAutoConfiguration.class)
```

- in `logback.xml` (make sure it's lowecase `logback.xml`), disable logging to breadcrumbs:

```xml
<appender name="Sentry" class="io.sentry.logback.SentryAppender">
  <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
    <level>WARN</level>
  </filter>
  <minimumBreadcrumbLevel>OFF</minimumBreadcrumbLevel>
</appender>
```

**Comment by adinauer** [comment] 2022-04-19 13:08
Duplicate of https://github.com/getsentry/sentry-java/issues/1790

**Closed by adinauer** 2022-04-19 13:08 UTC
Labels: bug, spring-boot, Platform: Java, WebFlux, Status: Backlog
