### ISSUE TITLE
io.sentry.android.core.internal.gestures.WindowCallbackAdapter.dispatchTouchEvent (WindowCallbackAdapter.java:39)

### ISSUE THREAD

**Issue by daniel-waiguru** [getsentry/sentry-java#2919] opened 2023-09-06 06:26 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.1.0

### Proguard

Disabled

### Version

3.5.0

### Steps to Reproduce

Exception captured on Crashlytics 
`
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
       at java.util.ArrayList.clear(ArrayList.java:569)
       at android.view.ViewGroup.buildOrderedChildList(ViewGroup.java:4335)
       at android.view.ViewGroup.buildTouchDispatchChildList(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4012)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
       at io.sentry.android.core.internal.gestures.WindowCallbackAdapter.dispatchTouchEvent(WindowCallbackAdapter.java:39)
       at io.sentry.android.core.internal.gestures.SentryWindowCallback.dispatchTouchEvent(SentryWindowCallback.java:64)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
       at android.view.View.dispatchPointerEvent(View.java:14213)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5653)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5456)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4959)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5012)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4978)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5118)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4986)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5175)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4959)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5012)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4978)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4986)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4959)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7682)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7651)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7612)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7807)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
`

### Expected Result

N/A

### Actual Result

N/A

**Comment by romtsn** [comment] 2023-09-06 09:30
hi @daniel-waiguru, actually the root cause is somewhere in the top of the stacktrace:
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3 at java.util.ArrayList.clear(ArrayList.java:569) at android.view.ViewGroup.buildOrderedChildList(ViewGroup.java:4335) at 
```

The sentry frames just happened to be there because of our UI auto-instrumentation, where we collect clicks as breadcrumbs. You can see that our code just delegates to the parent class without any additional logic here: https://github.com/getsentry/sentry-java/blob/540b4669e36ca03463035e5fba8d405607804b3e/sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/WindowCallbackAdapter.java#L37-L40

I'm going to close this issue as it's not actionable for us, but feel free to comment here if you find out that our SDK is still the root cause. Thank you

**Closed by romtsn** 2023-09-06 09:30 UTC
Labels: Type: Bug, Platform: Android, Platform: Java, Waiting for: Product Owner
