### ISSUE TITLE
io.sentry.JsonSerializer.<init> ANR triggered by slow operations in main thread

### ISSUE THREAD

**Issue by seven415** [getsentry/sentry-java#3583] opened 2024-07-18 09:18 UTC
### Description

com.android.tools.build:gradle:7.3.1

SDK Version:7.9.0

log from firebase:

java.lang.Object.hashCode (Object.java:122)
java.util.HashMap.hash (HashMap.java:336)
java.util.HashMap.put (HashMap.java:608)
io.sentry.JsonSerializer.<init> (JsonSerializer.java:113)
io.sentry.SentryOptions.<init> (SentryOptions.java:122)
io.sentry.SentryOptions.empty (SentryOptions.java:2495)
io.sentry.NoOpHub.<init> (NoOpHub.java:22)
io.sentry.NoOpHub.<clinit> (NoOpHub.java:16)
io.sentry.Sentry.<clinit> (Sentry.java:47)
io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:87)
io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:58)
io.sentry.android.core.SentryInitProvider.onCreate (SentryInitProvider.java)
android.content.ContentProvider.attachInfo (ContentProvider.java:2468)
android.content.ContentProvider.attachInfo (ContentProvider.java:2433)
io.sentry.android.core.SentryInitProvider.attachInfo (SentryInitProvider.java:39)
android.app.ActivityThread.installProvider (ActivityThread.java:7867)
android.app.ActivityThread.installContentProviders (ActivityThread.java:7378)
ccc.rrr.hhh.s.a.setEnd (Native method)
ccc.rrr.hhh.s.a.attachBaseContext (a.java:82)
android.app.Application.attach (Application.java:355)
android.app.Instrumentation.newApplication (Instrumentation.java:1251)
android.app.LoadedApk.makeApplicationInner (LoadedApk.java:1485)
android.app.LoadedApk.makeApplicationInner (LoadedApk.java:1422)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7087)
android.app.ActivityThread.-$$Nest$mhandleBindApplication (unavailable)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2220)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:211)
android.os.Looper.loop (Looper.java:300)
android.app.ActivityThread.main (ActivityThread.java:8296)
java.lang.reflect.Method.invoke (Native method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:559)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:954)

**Comment by kahest** [comment] 2024-07-19 13:13
Hi @seven415 can you share your Sentry configuration? Can you reproduce this locally with a minimal setup? And do you also see other ANR events on startup/initialization of your app? If something blocks the main thread extensively, the stack traces of reported ANRs might not be reliable.

related:
https://github.com/getsentry/sentry-java/issues/3584
https://github.com/getsentry/sentry-java/issues/3585
might have the same root cause, all happening during initialization

**Comment by seven415** [comment] 2024-07-22 08:09
It cannot be reproduced locally. These ANRs are all seen from firebase.
7 days data：


![Image](https://github.com/user-attachments/assets/c7e84e19-9856-41f6-b752-f344c934c5d9)

**Comment by kahest** [comment] 2024-07-22 08:19
@seven415 can you share your Sentry options? Do you also see other ANR events on startup/initialization of your app? If something blocks the main thread extensively, the stack traces of reported ANRs might not be reliable.

**Comment by seven415** [comment] 2024-07-22 08:23
@kahest 

![Image](https://github.com/user-attachments/assets/0d979b56-b010-4437-ba26-1d081bee1bde)

**Comment by markushi** [comment] 2024-07-24 13:08
@seven415 thanks for reporting this issue. We're closing this in favor of https://github.com/getsentry/sentry-java/issues/2541, which is a similar issue.

**Closed by markushi** 2024-07-24 13:08 UTC
Labels: Platform: Android
