### ISSUE TITLE
Handle IOExceptions gracefully - No space left on device crash

### ISSUE THREAD

**Issue by prashanOS** [getsentry/sentry-java#2250] opened 2022-09-21 00:37 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.0

### Proguard

Enabled

### Version

6.4.1

### Steps to Reproduce

We're seeing this in production, haven't been able to reproduce locally.

Stack trace:
```
android.system.ErrnoException: write failed: ENOSPC (No space left on device)
    at libcore.io.Linux.writeBytes(Linux.java)
    at libcore.io.Linux.write(Linux.java:288)
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:348)
    at libcore.io.IoBridge.write(IoBridge.java:526)
    at java.io.FileOutputStream.write(FileOutputStream.java:381)
    at java.io.FileOutputStream.write(FileOutputStream.java:359)
    at io.sentry.instrumentation.file.SentryFileOutputStream.lambda$write$1
    at io.sentry.instrumentation.file.SentryFileInputStream$$InternalSyntheticLambda$0$c9de00094f36f7181c256cabb0018db2e9770514b78c32df68ca65010e17e362$0.call$bridge(SourceFile:0)
    at io.sentry.instrumentation.file.FileIOSpanManager.performIO(SourceFile:48)
    at io.sentry.instrumentation.file.SentryFileOutputStream.write(SourceFile:102)
    at com.amplitude.core.utilities.EventsFileManager.writeToFile(SourceFile:169)
    at com.amplitude.core.utilities.EventsFileManager.finish(SourceFile:145)
    at com.amplitude.core.utilities.EventsFileManager.rollover(SourceFile:104)
    at com.amplitude.android.utilities.AndroidStorage.rollover
    at com.amplitude.core.platform.EventPipeline$upload$1$1$1.invokeSuspend(SourceFile:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
    at kotlinx.coroutines.DispatchedTask.run(SourceFile:106)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
java.io.IOException: write failed: ENOSPC (No space left on device)
    at libcore.io.IoBridge.write(IoBridge.java:531)
    at java.io.FileOutputStream.write(FileOutputStream.java:381)
    at java.io.FileOutputStream.write(FileOutputStream.java:359)
    at io.sentry.instrumentation.file.SentryFileOutputStream.lambda$write$1
    at io.sentry.instrumentation.file.SentryFileInputStream$$InternalSyntheticLambda$0$c9de00094f36f7181c256cabb0018db2e9770514b78c32df68ca65010e17e362$0.call$bridge(SourceFile:0)
    at io.sentry.instrumentation.file.FileIOSpanManager.performIO(SourceFile:48)
    at io.sentry.instrumentation.file.SentryFileOutputStream.write(SourceFile:102)
    at com.amplitude.core.utilities.EventsFileManager.writeToFile(SourceFile:169)
    at com.amplitude.core.utilities.EventsFileManager.finish(SourceFile:145)
    at com.amplitude.core.utilities.EventsFileManager.rollover(SourceFile:104)
    at com.amplitude.android.utilities.AndroidStorage.rollover
    at com.amplitude.core.platform.EventPipeline$upload$1$1$1.invokeSuspend(SourceFile:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
    at kotlinx.coroutines.DispatchedTask.run(SourceFile:106)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
    
```

### Expected Result

IOExceptions are handled gracefully - no crash.

### Actual Result

Crash.

**Comment by adinauer** [comment] 2022-09-21 06:04
Hello @prashanOS, are you using File Instrumentation of the Sentry Android Gradle Plugin? If so that's just wrapping your streams and thus shows up in stack traces. Looks to me likes this would have to be handled inside amplitude to avoid the crash. See these lines in the stacktrace:

```
at com.amplitude.core.utilities.EventsFileManager.writeToFile(SourceFile:169)
at com.amplitude.core.utilities.EventsFileManager.finish(SourceFile:145)
at com.amplitude.core.utilities.EventsFileManager.rollover(SourceFile:104)
at com.amplitude.android.utilities.AndroidStorage.rollover
at com.amplitude.core.platform.EventPipeline$upload$1$1$1.invokeSuspend(SourceFile:102)
```

We're just catching the exception, update the span with it and then rethrow. This should mimic the behaviour of the wrapped stream.

**Comment by romtsn** [comment] 2022-09-21 09:15
@adinauer could this be related to the latest fix with open FileDescriptors? (because we keep them open, eventually the device runs out of disk space)

**Comment by adinauer** [comment] 2022-09-21 14:12
Closing as this doesn't seem to be caused by Sentry. In case you run into any more issues, please feel free to reopen.

**Closed by adinauer** 2022-09-21 14:12 UTC
Labels: Platform: Android, Platform: Java
