### ISSUE TITLE
can not initialize sentry inside tomcat ServetContextLister or ServletContainerListener

### ISSUE THREAD

**Issue by naxmefy** [getsentry/sentry-java#1946] opened 2022-03-11 18:25 UTC
### Integration

sentry

### Java Version

8

### Version

5,6,2

### Steps to Reproduce

1. load our 10~20 years old java code
2. execute it on a tomcat 8
3. get the error inside a simple servletcontainerlist or the java default one inside a servlet context listener

### Expected Result

it should initliaze and not throw a VerifyError - testet with a simple main function - it works

### Actual Result

it throws a VerifyError

```
java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2394)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	at io.sentry.EnvelopeReader.<init>(EnvelopeReader.java:22)
	at io.sentry.SentryOptions.<init>(SentryOptions.java:90)
	at io.sentry.SentryOptions.empty(SentryOptions.java:1595)
	at io.sentry.NoOpHub.<init>(NoOpHub.java:15)
	at io.sentry.NoOpHub.<clinit>(NoOpHub.java:13)
	at io.sentry.Sentry.<clinit>(Sentry.java:24)
	at app.core.CampusSetup.startCampus(CampusSetup.java:115)
	at app.listener.ApplicationStartListener.contextInitialized(ApplicationStartListener.java:101)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1719)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:479)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:428)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```java
public class ApplicationStartListener implements ServletContextListener {
    // ...
    public void contextInitialized(ServletContextEvent evt) {
        // ... load some config strings 
        // ... check strings are fine
        CampusSetup.startCampus(ctx);
        // ... do more init stuff
    }

    // ...
}

public class CampusSetup {
    // ...
    public static void startCampus(ServletContext ctx) {
        // ... check some paths
        // ... load some app specific properties
        // ... check some properties
        Sentry.init(sentryOptions -> {
            sentryOptions.setDsn("http://xxxx@host:port/2");
            sentryOptions.setServerName("host1");
    
            sentryOptions.setEnvironment("dev");
            sentryOptions.setRelease("app@1.1.0");
            sentryOptions.setTag("institute", "xxxx");
            sentryOptions.setTag("developer", "xxxx");
            sentryOptions.setDebug(true);
            sentryOptions.setSampleRate(0.5);
            sentryOptions.setTracesSampleRate(0.2);
        });
        // ... load datasources
        // ... load god and the world
    }
    // ...
}
```

**or**

```java
package app.servlet;

import io.sentry.Sentry;

import javax.servlet.ServletContainerInitializer;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import java.util.Set;

public class SentryServletContainerInitializer implements ServletContainerInitializer {
    @Override
    public void onStartup(Set<Class<?>> set, ServletContext servletContext) throws ServletException {
        Sentry.init(sentryOptions -> {
            sentryOptions.setDsn("http://xxxx@host:port/2");
            sentryOptions.setServerName("host1");
    
            sentryOptions.setEnvironment("dev");
            sentryOptions.setRelease("app@1.1.0");
            sentryOptions.setTag("institute", "xxxx");
            sentryOptions.setTag("developer", "xxxx");
            sentryOptions.setDebug(true);
            sentryOptions.setSampleRate(0.5);
            sentryOptions.setTracesSampleRate(0.2);
        });
    }
}
```

and the log

```
	org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/web]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1719)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:479)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:428)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
		at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
		at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
		at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
		at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
		at sun.rmi.transport.Transport$1.run(Transport.java:200)
		at sun.rmi.transport.Transport$1.run(Transport.java:197)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
		at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.VerifyError: Cannot inherit from final class
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2394)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
		at io.sentry.EnvelopeReader.<init>(EnvelopeReader.java:22)
		at io.sentry.SentryOptions.<init>(SentryOptions.java:90)
		at io.sentry.SentryOptions.empty(SentryOptions.java:1595)
		at io.sentry.NoOpHub.<init>(NoOpHub.java:15)
		at io.sentry.NoOpHub.<clinit>(NoOpHub.java:13)
		at io.sentry.Sentry.<clinit>(Sentry.java:24)
		at app.servlet.SentryServletContainerInitializer.onStartup(SentryServletContainerInitializer.java:13)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5144)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 44 more
```

**Comment by maciejwalkowiak** [comment] 2022-03-14 09:50
Thanks for reporting.

- what Java version are you using?
- is application packaged as `war` and sentry dependencies are inside the war package, or Sentry (with its dependencies) are somewhere else in Tomcat classpath?
- which Sentry SDK modules are you using? Just `sentry` or `sentry` and `sentry-servlet`? We've made `sentry-servlet` for non-spring servlet based applications so perhaps you can take a look at it.

**Comment by chadwhitacre** [comment] 2022-03-15 19:16
@bruno-garcia Can we move this from Untriaged to Needs Info? 🙏

**Comment by naxmefy** [comment] 2022-03-15 19:36
> Thanks for reporting.
> 
> * what Java version are you using?
> * is application packaged as `war` and sentry dependencies are inside the war package, or Sentry (with its dependencies) are somewhere else in Tomcat classpath?
> * which Sentry SDK modules are you using? Just `sentry` or `sentry` and `sentry-servlet`? We've made `sentry-servlet` for non-spring servlet based applications so perhaps you can take a look at it.

1. Oracle 1.8.0_261
2. as war and sentry deps are inside (tested with war:exploded on Tomcat 8.5.58)
3. Tested
  - first test with "just `sentry`" from `ServletContextListener`
  - second test with "`sentry-servlet`" and `ServletContainerInitializer`

**Comment by maciejwalkowiak** [comment] 2022-03-17 10:05
Unfortunately I am not able to reproduce. Please take a look at sample application: https://github.com/maciej-scratches/sentry-spring-war-sample

I've run it with:

- Java 8:

openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Zulu 8.48.0.51-CA-macosx) (build 1.8.0_262-b19)

- Tomcat 8.5.70

Take a look if this application works with on your environment. You can also provide a sample application that is failing for you so we can investigate further.

**Comment by marandaneto** [comment] 2022-03-29 08:04
@naxmefy did you check this out?

**Comment by naxmefy** [comment] 2022-03-29 16:41
> @naxmefy did you check this out?

@marandaneto tested it with another simple example on our tomcat (https://github.com/naxmefy/sentry-servlet-example). It works. But not with our primary codebase. Now i found out that it seems that our dependency structure could maybe the problem. In this case i use maven to manage the build. But we the most deps are directly managed in our source (WEB-INF/lib). 

The VerifyError is triggered in the class load process of a gson Class. And i don't get it 😭 

Thank you for your support 💐

**Comment by marandaneto** [comment] 2022-03-30 06:21
Gson should be min. 2.7, See note https://docs.sentry.io/platforms/java/#install
The major version of the SDK 6.0.0 preview vendors Gson, so it's dependency free, try it out https://github.com/getsentry/sentry-java/releases/tag/6.0.0-alpha.4
Closing this issue since it looks like an environment issue rather than an SDK issue.

**Closed by marandaneto** 2022-03-30 06:21 UTC
Labels: waiting for feedback, Platform: Java
