### ISSUE TITLE
Events from same method always grouped into same group w/ sentry-logback

### ISSUE THREAD

**Issue by shimpeko** [getsentry/sentry-java#396] opened 2017-05-09 05:59 UTC
I've noticed all events from a function grouped into same group w/ sentry-logback.

With sentry-logback, all events will have `exception interface` or `stacktrace interface`. Since one of [this if-else clause](https://github.com/getsentry/raven-java/blob/master/raven-logback/src/main/java/com/getsentry/raven/logback/SentryAppender.java#L291) will always be true.

This means when we send log like `logger.warn("hoge")`, this event's interface will always be `stacktrace interface` (and I believe it will never be [event with `message interface`](https://github.com/getsentry/raven-java/blob/master/raven-logback/src/main/java/com/getsentry/raven/logback/SentryAppender.java#L285)).

In sentry side, grouping of events with stacktrace interface is decided [at this method](https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/stacktrace.py#L359). And with sentry-logback which will not send `context_line attribute`, grouping will be done by just file name, class name and method name.

This result in titled situation, "Events from same method always grouped into same group w/ sentry-logback".

Note: The `fingerprint` can be used in this kind of situation. But raven-logback is not supporting it.

**Comment by bretthoerner** [comment] 2017-05-09 17:00
Hey @shimpeko 

I agree this is an issue. I'll look into it.

Thanks

**Comment by bretthoerner** [comment] 2017-05-22 22:18
Created https://github.com/getsentry/sentry/pull/5428

**Comment by bretthoerner** [comment] 2017-05-31 20:13
Merged that PR, should fix on next deploy.

**Comment by bretthoerner** [comment] 2017-06-01 00:08
This actually had to be reverted here: https://github.com/getsentry/sentry/commit/439c413d803bbffcc38b03f8fe73fd446dafb80e

The problem is that parameterized logging support is very bad. If people log something like `log.warn("Error with user {}", userId)` then each of those becomes its own error.

We need a way to fix this for both "sides" of the issue.

**Comment by marandaneto** [comment] 2020-10-01 09:39
@maciejwalkowiak do you know if this is still an issue?

**Comment by maciejwalkowiak** [comment] 2020-10-01 10:58
I don't exactly understand the issue. Perhaps a code snippet that illustrates the problem would be handy.

**Comment by bruno-garcia** [comment] 2020-10-01 20:58
> Note: The fingerprint can be used in this kind of situation. But raven-logback is not supporting it.


We support fingerprint on 3.0:

```java
Sentry.withScope(s -> {
s.setFingerprint(...);
logger.warn(..);
});
```

**Closed by bruno-garcia** 2020-10-01 20:58 UTC
Labels: Logback
