### ISSUE TITLE
JavaFX integration

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1743] opened 2021-09-27 17:15 UTC
A potential desktop focused integration for JavaFX.

* Collect Device Info. See [this](https://github.com/getsentry/sentry-java/issues/697)
* It could include the Screenshot feature. See [this](https://stackoverflow.com/questions/18024498/taking-a-screenshot-of-a-scene-or-a-portion-of-a-scene-in-javafx-2-2) and [this](https://github.com/getsentry/develop/pull/422)
* Release Health support #1742
  * JavaFX: Does it have hooks to foreground/background? We could have release health  
* Page load performance monitoring
  * If there's a hook for a page load, we can start a transaction automatically and end with idle timeout 
* Offline caching of events
* breadcrumbs for app lifecycle

**Comment by adinauer** [comment] 2022-04-19 12:49
Duplicate of https://github.com/getsentry/sentry-java/issues/1996

**Closed by adinauer** 2022-04-19 12:49 UTC
Labels: enhancement, JavaFX, Platform: Java, Desktop
