### ISSUE TITLE
ANRs reported Google play console

### ISSUE THREAD

**Issue by Nitin-UpSwing** [getsentry/sentry-java#3113] opened 2023-12-20 07:53 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.0.2

### Proguard

Enabled

### Version

6.23.0

### Steps to Reproduce

ANRs are happening randomly

### Expected Result

ANR should not happen

### Actual Result

App is crashing , please check the attached screen shot from google play console
<img width="961" alt="image001" src="https://github.com/getsentry/sentry-java/assets/122961577/236d9c1b-6101-4994-8095-b24edbe05298">

**Comment by romtsn** [comment] 2023-12-20 09:14
I don't see any ANRs in the screenshot, did you mean to attach a different screenshot? Please provide stacktraces, devices on which crashes are happening and in general as much details as possible that can help us investigate the issue.

**Comment by Nitin-UpSwing** [comment] 2023-12-20 09:57
> I don't see any ANRs in the screenshot, did you mean to attach a different screenshot? Please provide stacktraces, devices on which crashes are happening and in general as much details as possible that can help us investigate the issue.

Hi will share the logs in sometime today

**Comment by Nitin-UpSwing** [comment] 2023-12-21 06:10
Hi @romtsn please find attached logs
[stacktrace (1).log](https://github.com/getsentry/sentry-java/files/13736848/stacktrace.1.log)
[stacktrace.log](https://github.com/getsentry/sentry-java/files/13736850/stacktrace.log)

**Comment by kahest** [comment] 2023-12-21 08:27
@Nitin-UpSwing I don't see any reference of Sentry at all in those stacktraces, did you attach the correct files?

**Comment by Nitin-UpSwing** [comment] 2023-12-21 09:07
> @Nitin-UpSwing I don't see any reference of Sentry at all in those stacktraces, did you attach the correct files?

Sorry @kahest let me check with my team for proper logs

**Comment by Nitin-UpSwing** [comment] 2023-12-22 11:08
> @Nitin-UpSwing I don't see any reference of Sentry at all in those stacktraces, did you attach the correct files?

Hi @kahest 
here the logs that I got from play store:

```
SDK provider note

Description automatically generated Sentry Android Corebrightness_1io.sentry:sentry-android-corebrightness_128 Feb


Crash status : Known issue (won't fix)

Note

The issue is either caused by the consumer application or by the Android SDK itself, our WindowCallbackAdapter stack frames just happened to be there because of our UI breadcrumbs instrumentation. The WindowCallbackAdapter does not do anything besides delegating the call to the next Window.Callback. https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/WindowCallbackAdapter.java
```

**Comment by Nitin-UpSwing** [comment] 2023-12-26 06:46
Hi @kahest 

Can you please help to solve above issue because it is happening for live user and it impacting our user experience?

**Comment by markushi** [comment] 2023-12-27 06:42
Hi @Nitin-UpSwing, thanks for providing more details.

the logs from the Google Play Console are provided by us, explaining why the ANR is not caused by our sentry SDK.
If you can provide stacktraces which contain any SDK code (`io.sentry.*` package) we'd be happy to have a look!

Both stacktraces provided above are pointing to `androidx.constraintlayout.widget.ConstraintLayout` though, so maybe have a look there?

**Comment by Nitin-UpSwing** [comment] 2023-12-27 07:35
> Hi @Nitin-UpSwing, thanks for providing more details.
> 
> the logs from the Google Play Console are provided by us, explaining why the ANR is not caused by our sentry SDK. If you can provide stacktraces which contain any SDK code (`io.sentry.*` package) we'd be happy to have a look!
> 
> Both stacktraces provided above are pointing to `androidx.constraintlayout.widget.ConstraintLayout` though, so maybe have a look there?

But that issue due to sentry blocking the UI as said in notes provide by google play console

**Comment by markushi** [comment] 2023-12-27 10:06
Let me try to clarify this: The note you're seeing on the Google Play Console is provided by us, the sentry SDK team.

> The issue is either caused by the consumer application or by the Android SDK itself, our
WindowCallbackAdapter stack frames just happened to be there because of our UI breadcrumbs
instrumentation.

Here we clearly try to explain that the underlying issue is either inside your app or the Android SDK, but not within sentry's `WindowCallbackAdapter`, as it simply calls `super.dispatchTouchEvent()`, [link here](https://github.com/getsentry/sentry-java/blob/8952d0f64c218de20c29105b0e21420280b172df/sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/SentryWindowCallback.java#L64C1-L64C50).

If you can provide a stacktrace which includes `io.sentry.*` frames, we're happy to take a look at this.

**Comment by stefanosiano** [comment] 2024-01-10 14:21
Closing, since the issue is inside the app, as sentry's WindowCallbackAdapter simply calls super.dispatchTouchEvent(), [link here](https://github.com/getsentry/sentry-java/blob/8952d0f64c218de20c29105b0e21420280b172df/sentry-android-core/src/main/java/io/sentry/android/core/internal/gestures/SentryWindowCallback.java#L64C1-L64C50).

**Closed by stefanosiano** 2024-01-10 14:21 UTC
Labels: Type: Bug, Platform: Android, Waiting for: Community
