### ISSUE TITLE
Screenshot causes crash

### ISSUE THREAD

**Issue by hosseinaminii** [getsentry/sentry-java#2520] opened 2023-02-06 09:02 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.1.3

### Proguard

Enabled

### Version

6.13.0

### Steps to Reproduce

1. Enable the screenshot feature 
2. Check for HTTP errors (by adding SentryOkHttpInterceptor to the Okhttp or other ways)
3. After scrolling lists, if there are HTTP failures in several items for example while fetching images, the app crashes

### Expected Result

No exception 

### Actual Result

java.lang.IllegalArgumentException: Failed requirement.
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:567)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:774)
                                                                                                    	at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:216)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:999)
                                                                                                    	at android.view.View.draw(View.java:19126)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:18073)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:18032)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:18032)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:18032)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:18032)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:18032)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:18032)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2980)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2794)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2347)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:789)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by romtsn** [comment] 2023-02-06 10:57
hi @hosseinaminii, could you please share full stacktrace of the crash?

**Comment by hosseinaminii** [comment] 2023-02-06 12:20
I update the issue
The app is written in Compose and it happens in LazyColumn

**Comment by romtsn** [comment] 2023-02-07 08:52
@hosseinaminii hrm, but there are no sentry frames in the stacktrace, why do you think it's our SDK that is causing problems?

For what it's worth, we also wrap the screenshot-taking code into try-catch [here](https://github.com/getsentry/sentry-java/blob/f6a135d1ef81f9cd70d72608e8beb8c2103f69bd/sentry-android-core/src/main/java/io/sentry/android/core/internal/util/ScreenshotUtils.java#L37-L58), so I am not sure our code can cause crashes.

Lastly, there are several entries on the google issue tracker which seem to have the same stacktrace, so it looks like the issue on the compose side itself?
https://issuetracker.google.com/issues/259295561
https://issuetracker.google.com/issues/265411781

**Comment by hosseinaminii** [comment] 2023-02-07 09:35
@romtsn you're right there are no sentry frames in the stacktrace and I couldn't realize why it happens at first until I removed the sentry screenshot and the crash gone. 
I think there are some sort of conflicts between Compose and Sentry screenshot. 
We haven't published the new version of our app yet but in the internal testing, there was no reports about this crash anymore, after publishing I'll give you the feedback in a larger range of users

**Comment by romtsn** [comment] 2023-02-07 09:42
@hosseinaminii alright, would it be possible to provide a reproducible sample?

**Comment by hosseinaminii** [comment] 2023-02-07 09:55
@romtsn Ok, I'll create a sample project and share it with you

**Comment by romtsn** [comment] 2023-02-22 14:48
@hosseinaminii hey, have you had a chance to reproduce this?

**Comment by romtsn** [comment] 2023-03-08 14:51
@hosseinaminii the issue stayed unanswered for a over a month. If you managed to provide a reproducible sample, we'll reopen the issue, but for now we're gonna close this. Thank you!

**Closed by romtsn** 2023-03-08 14:51 UTC
Labels: Type: Bug, Platform: Android, waiting for feedback
