### ISSUE TITLE
Sentry fails to upload with ProGuard: silent NullPointerException in JsonMarshaller.writeExtras

### ISSUE THREAD

**Issue by mcomella** [getsentry/sentry-java#572] opened 2018-03-30 23:16 UTC
Using sentry 1.7.2 on Android, I am able to upload without ProGuard (on my debug builds) but I fail on non-debug builds with ProGuard (note: obfuscation is off). The exception is thrown here, where `extras` is null: https://github.com/getsentry/sentry-java/blob/38aaffa2d863fdc858cc5f9b24ff2e87d14b5a7a/sentry/src/main/java/io/sentry/marshaller/json/JsonMarshaller.java#L247-L249

And it's silently suppressed so as an end user of Sentry, I don't see any logs and Sentry mysteriously fails to upload.

To repro, here's a copy of my code: https://github.com/mcomella/firefox-tv/tree/host-sentry-npe Notes:
- You'll have to build with the `amazonWebviewRelease` build variant
- You'll have to sign the APK in order to install it on device (as is the case with release builds)

To repro:
- Add a debugger statement on the line I mention above
- Run the app and crash it. I added code so that you can force a crash once by pressing any button once you're on the home screen (with the "Enter a search" text field)
- Reopen the app.
- Attach a debugger to the running app
- Wait ~60s for the background thread to attempt to upload and wait for the debugger to catch

## Workaround
I was able to fix the problem by keeping the `Event` class: I noticed it gets serialized to disk so I'm guessing ProGuard is removing fields that are important for the Serialization process. Here's my proguard config for sentry:

```
# Recommended config
-keepattributes LineNumberTable,SourceFile
-dontwarn org.slf4j.**
-dontwarn javax.**

# My addition
-keep class io.sentry.event.Event { *; }
```

**Comment by bretthoerner** [comment] 2018-04-01 13:52
Ah crap, yeah we do some special magic to try and handle serializing extras since it's arbitrary `Object`s. Good catch, I'll add this to the docs but also check for the `null` incase deserialization fails I guess?

**Comment by bretthoerner** [comment] 2018-04-01 19:13
@mcomella Do you mind reviewing https://github.com/getsentry/sentry-java/pull/573 ?

Thanks for the report and debugging it!

**Comment by bretthoerner** [comment] 2018-04-03 15:08
@mcomella I actually dislike my `getExtra` hack.

I'm now trying to reproduce this locally, I have a debug build with Proguard enabled where I write an Event to a file and read it back and `extras` is working for me. I can't get it to be `null`. Is there any chance you could help me come up with a simple repro? Do you do anything you consider unique with your Proguard or `extras`?

I'm basically running this project (but I enabled Proguard for debug): https://github.com/getsentry/examples/tree/master/android

And I'm doing this silly thing currently, which is exactly what Sentry SDK does internally:

```java
            Event writeEvent = new EventBuilder().withExtra("foo", "bar").build();
            
            File file = new File(cacheDir, "test");
            FileOutputStream fileOutputStream = new FileOutputStream(file);
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);
            objectOutputStream.writeObject(writeEvent);

            FileInputStream fileInputStream = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fileInputStream);
            Event readEvent = (Event) ois.readObject();
            String foo = (String) readEvent.getExtra().get("foo");
            System.out.println("\n\n\n" + foo + "\n\n\n");
```

**Comment by mcomella** [comment] 2018-04-04 23:30
See my speculation on why ProGuard is breaking my build [in the PR](https://github.com/getsentry/sentry-java/pull/573#issuecomment-378774939). I'm guessing your code is calling `readObject` and `writeObject` (through objectOutputStream) so that ProGuard is not explicitly removing it.

> Do you do anything you consider unique with your Proguard or extras?

Not that I'm aware of...

To STR how I did it:
- Clone [our repository](https://github.com/mozilla-mobile/firefox-tv)
- Checkout https://github.com/mozilla-mobile/firefox-tv/commit/6fb08e9ad165e615a5b715433c9ac82869b465ff
- Open proguard-rules.pro and remove the `-keep class io.sentry.event.Event { *; }` line
- Add a `<project-dir>/.sentry_dsn_release` file with your DSN (no newline at the end of the file)
- Add code to force a crash (for testing Sentry upload), e.g. add a `throw` in `MainActivity.dispatchKeyEvent` so it crashes when a key is pressed
- Build the amazonWebviewBeta variant (you'll see gradle output saying whether the key inclusion was successful)
- Open the app and force a crash (e.g. press a key if you added the code)
- Open the app again and wait for Sentry upload

Expected: Sentry uploads
Actual: Silently fails as described in the first comment

You can add a debugger statement in the Sentry code (e.g. in JsonMarshaller.writeExtras) to watch where the exception is thrown, rather than just waiting a while to notice that upload fails.

**Comment by bretthoerner** [comment] 2018-04-09 15:51
Odd, the following is in the `usage.txt` for my test project too:

```
io.sentry.event.Event:
    302:304:private void readObject(java.io.ObjectInputStream)
    308:310:private void writeObject(java.io.ObjectOutputStream)
```

**Comment by marandaneto** [comment] 2020-01-03 10:24
@mcomella hey, a lot of fixes were made since then, do you mind trying the latest version and see if it still happens? thanks

**Comment by marandaneto** [comment] 2020-01-31 13:13
@mcomella closing this issue, if you see that is still happening, let us know :)

**Closed by marandaneto** 2020-01-31 13:13 UTC
Labels: Android, bug, help wanted
