### ISSUE TITLE
Android ANR

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry-java#3126] opened 2024-01-03 02:27 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

1.7.36

### Proguard

Enabled

### Version

6.27.0

### Steps to Reproduce

Direct operation

### Expected Result

no ANR

### Actual Result

There have been a lot of recent ANR occurrences with Sentry that were not there before Sentry。
<img width="1136" alt="截屏2023-12-29 15 12 23" src="https://github.com/getsentry/sentry-java/assets/13718172/aa685eee-8892-4679-ab08-4f52cd87689d">
![Uploading 截屏2023-12-29 15.15.43.png…]()

**Comment by romtsn** [comment] 2024-01-03 08:25
sorry, there's not enough details for us to reproduce/look at it, so I'm afraid this is not really actionable. I can suggest you to upgrade to version [7.0.0](https://github.com/getsentry/sentry-java/releases/tag/7.0.0) or above of the SDK, where we've made several improvements with regards to ANRs caused by the SDK.

I'm going to close this issue, but if you get more actionable stacktraces (e.g. with the Sentry SDK frames in them), feel free to post them on this issue. Thank you

**Closed by romtsn** 2024-01-03 08:25 UTC
Labels: Type: Bug, Platform: Android, Platform: Java, Waiting for: Product Owner
