### ISSUE TITLE
public Breadcrumb() causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nienienienie** [getsentry/sentry-java#2237] opened 2022-09-08 09:30 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

5.7.3

### Steps to Reproduce

1. Android SDK 31
2. call constructor Breadcrumb()
3. I'm getting exception on production
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=1
    at java.util.Locale.getDefault(Locale.java:928)
    at java.util.Calendar.getInstance(Calendar.java:1639)
```

https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-31/blob/2c56b25f619575bea12f9c5520ed2259620084ac/java/util/Calendar.java#L1639

https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-31/blob/2c56b25f619575bea12f9c5520ed2259620084ac/java/util/Locale.java#L928

### Expected Result

No exception

### Actual Result

Exception

**Comment by adinauer** [comment] 2022-09-09 07:23
Hello @nienienienie I'm unable to reproduce the issue. Is this happening only on certain devices?

**Comment by nienienienie** [comment] 2022-09-14 09:43
Yes, it's happened only once, but it did happen on production app installed from Play Store for device Android 11 / SM-A127F.

**Comment by adinauer** [comment] 2022-09-15 12:14
Hmm has the device been rooted? You can check on the event what the value of `os.rooted` says. Maybe someone's been messing with their device?

**Comment by nienienienie** [comment] 2022-09-16 08:22
no, os.rooted is false

**Comment by nienienienie** [comment] 2022-09-16 08:23
but I see it's emulator, sdk_gphone64_arm64

**Comment by adinauer** [comment] 2022-09-16 10:47
Hmm then I have no good explanation to give you at the moment - sorry.

**Comment by adinauer** [comment] 2022-09-23 10:00
Closing this as we don't know how to reproduce. If you can provide any more info, feel free to reopen so we can take another look.

**Closed by adinauer** 2022-09-23 10:00 UTC
Labels: waiting for feedback, Platform: Java
