### ISSUE TITLE
Do not send session updates if `crashed` or `abnormal`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1548] opened 2021-06-22 07:40 UTC
maybe this is already working as expected, but we need to check the implementation also for hard crashes, app restart etc
https://develop.sentry.dev/sdk/sessions/#terminal-session-states

**Comment by bruno-garcia** [comment] 2021-06-22 13:10
It turns out the issue is more like: Don't send more than one session update with a terminal status.
The reason this is relevant is that guaranteeing the order is tricky before we get to the transport. More than one thread can call into the Hub's `capture` method which can create a 'session update' (think: error increment) but before reaching the transport they could get out-of-order. 

This is not an issue though (if using immutable snapshots as the session updates) as only a single session update will include the terminating status. Given that we atomically remove the session from the scope once are about to close it.

**Comment by bruno-garcia** [comment] 2021-07-21 14:15
We haven't heard any report from having this issue in mobile SDKs. We add the sdk.name to envelope headers so ingest folks can let us know what sdk name+version is affected.

**Closed by bruno-garcia** 2021-07-21 14:15 UTC
Labels: Android
