### ISSUE TITLE
Recursion Limit Hit Issue

### ISSUE THREAD

**Issue by humphriest** [getsentry/sentry-java#577] opened 2018-04-06 09:23 UTC
When printing out breadcrumbs on Android I am getting `<recursion limit hit>`. This is causing a problem when debugging errors by not showing much needed information.

https://github.com/getsentry/sentry-java/blob/027544f8a4063740294bde23073ea409d38ed5e1/sentry/src/main/java/io/sentry/marshaller/json/SentryJsonGenerator.java#L27-L31

This is where the variable `MAX_NESTING` is being set and applying the `<recursion limit hit>` message when recursion is over 3. Is it possible to remove this limit altogether or even higher it to a much larger number that won't hinder debugging?

**Comment by bretthoerner** [comment] 2018-04-12 14:07
The main issue is that events can be of a certain size. In addition, Jackson seems to offer no way for us to see how many bytes we have written so far, so that we could truncate by size.

And so since we know nothing about user's data structures we err towards accepting more events vs dropping them due to size.

We have an issue to make these options configurable, so I'm closing this as a dupe of #543.

**Closed by bretthoerner** 2018-04-12 14:07 UTC
