### ISSUE TITLE
SentryLogcatAdaptor consumes unnecessary time on main thread

### ISSUE THREAD

**Issue by kozaxinan** [getsentry/sentry-java#3430] opened 2024-05-17 13:20 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.4.0

### Proguard

Enabled

### Version

7.8.0

### Steps to Reproduce

Log a warning or error.
SentryLogcatAdapter calls addAsBreadcrumb.

### Expected Result

It should not take more time than calling log without Sentry.

### Actual Result

Gson operations takes a more than 3ms for every log operation.
That quickly aggregates for an app that has lots of log calls.

<img width="491" alt="Screenshot 2024-05-17 at 15 16 19" src="https://github.com/getsentry/sentry-java/assets/2559837/0f0d6601-daed-4e0c-959c-646bcac212d7">

[cpu-art-20240517T150036.trace.zip](https://github.com/getsentry/sentry-java/files/15349724/cpu-art-20240517T150036.trace.zip)

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2185) by [Unito](https://www.unito.io)

**Comment by kozaxinan** [comment] 2024-05-17 14:19
And we actually disable logo, scalebar and attribution after creating the view.

**Comment by kozaxinan** [comment] 2024-05-21 20:48
I come up with following solution.
I wonder if it would be better to disable NDK sync.

```
 val ndkScope = scopeObservers.firstOrNull { it is NdkScopeObserver }

                scopeObservers.apply {
                    remove(ndkScope)
                }

                if (ndkScope != null) {
                    addScopeObserver(
                        object : IScopeObserver by ndkScope {

                            override fun addBreadcrumb(crumb: Breadcrumb) {
                                coroutineScope.launch {
                                    ndkScope.addBreadcrumb(crumb)
                                }
                            }
                        }
                    )
                }
```

**Comment by stefanosiano** [comment] 2024-05-22 13:12
hi @kozaxinan, thanks for the report! 
We'll have a look at it soon! 
Probably related to https://github.com/getsentry/sentry-java/issues/3168

**Comment by romtsn** [comment] 2024-06-05 13:07
@kozaxinan we're going to close this as a duplicate of #3046, and reprioritize that one to tackle it sooner. Thanks for investigating this and providing us with data, please track it in the other issue 🙏

**Closed by romtsn** 2024-06-05 13:07 UTC
Labels: Type: Bug, Platform: Android, Sync: Jira
