### ISSUE TITLE
SDK版本从6.3.1升级至6.6.0后崩溃问题不上报

### ISSUE THREAD

**Issue by heiyl** [getsentry/sentry-java#2372] opened 2022-11-17 03:33 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

6.8

### Proguard

Enabled

### Version

6.6.0

### Steps to Reproduce

1、当前接入版本6.3.1可以正常上报崩溃问题
2、升级版本至6.6.0后崩溃问题在sentry上未能看到相关信息
3、再次升级至6.7.1后崩溃问题在sentry上也是上未能看到相关信息

### Expected Result

升级sentry的SDK版本至最新版本可以正常上报崩溃问题到sentry

### Actual Result

升级sentry的SDK版本至最新版本无法正常上报崩溃问题到sentry

**Comment by romtsn** [comment] 2022-11-17 08:31
hey, sorry for the problems. Did I understand it right, that it works again with version 6.7.1? Or what kind of relevant information you cannot see?

**Comment by heiyl** [comment] 2022-11-18 01:51
> hey, sorry for the problems. Did I understand it right, that it works again with version 6.7.1? Or what kind of relevant information you cannot see?

您好，理解反了，我的意思是 使用6.3.1版本可以正常捕获崩溃正常上报，使用6.7.1、6.7.0、6.6.0无法在sentry上看到崩溃信息的上报；是通过一下代码验证的：
findViewById(R.id.btnNum).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                throw new NullPointerException("这是一个测试空指针");
            }
        });

**Comment by heiyl** [comment] 2022-11-18 07:45
> > hey, sorry for the problems. Did I understand it right, that it works again with version 6.7.1? Or what kind of relevant information you cannot see?
> 
> 您好，理解反了，我的意思是 使用6.3.1版本可以正常捕获崩溃正常上报，使用6.7.1、6.7.0、6.6.0无法在sentry上看到崩溃信息的上报；是通过一下代码验证的： findViewById(R.id.btnNum).setOnClickListener(new View.OnClickListener() { @OverRide public void onClick(View v) { throw new NullPointerException("这是一个测试空指针"); } });

我尝试Debug断点调试跟中问题，在UncaughtExceptionHandlerIntegration类的uncaughtException(Thread thread, Throwable thrown)的方法中会捕获crash并进行异常上报，跟踪结束发现可以上报成功，日志如下：
2022-11-18 11:56:50.685 28939-28939/? I/Sentry: Uncaught exception received.
2022-11-18 11:56:57.694 28939-28939/? I/Sentry: Not possible to read external files directory
2022-11-18 11:56:57.707 28939-28939/? I/Sentry: Session is null on scope.withSession
2022-11-18 11:56:57.826 28939-30103/? W/Sentry: Current envelope doesn't exist.
2022-11-18 11:57:15.724 28939-28939/? I/Sentry: Invoking inner uncaught exception handler.
2022-11-18 11:57:27.260 30294-30294/? I/System.out: AuroraLogger>>>**** [Start ] taskName = DaojiaSentryTask
2022-11-18 11:57:27.261 30294-30336/? D/DaojiaSentryTask: DaojiaSentryTask: ==========================================
2022-11-18 11:57:27.377 30294-30336/? I/System.out: AuroraLogger>>>---- [Finish] taskName = DaojiaSentryTask, costTime = 116, offset = 85, threadName = Aurora#7

但是如果去掉断点，应该不会走或者还没来得及走UncaughtExceptionHandlerIntegration类的uncaughtException(Thread thread, Throwable thrown)的方法，因为日志并没有相关打印，参考日志：
2022-11-18 11:58:06.071 30786-30786/com.wuba.wbdaojia I/System.out: AuroraLogger>>>**** [Start ] taskName = DaojiaSentryTask
2022-11-18 11:58:06.071 30786-30821/com.wuba.wbdaojia D/DaojiaSentryTask: DaojiaSentryTask: ==========================================
2022-11-18 11:58:06.144 30786-30821/com.wuba.wbdaojia I/System.out: AuroraLogger>>>---- [Finish] taskName = DaojiaSentryTask, costTime = 73, offset = 79, threadName = Aurora#5

希望能根据以往内容可以定位到出现此问题的原因，谢谢！

**Comment by romtsn** [comment] 2022-11-18 08:23
do you initialize Sentry manually (e.g. `SentryAndroid.init`)? If yes, it might be the same bug as https://github.com/getsentry/sentry-java/issues/2373 which we'll fix today

**Comment by heiyl** [comment] 2022-11-18 10:20
> do you initialize Sentry manually (e.g. `SentryAndroid.init`)? If yes, it might be the same bug as #2373 which we'll fix today

是的，我们是手动初始化的，好的，修改后我们再升级验证，感谢！

**Comment by romtsn** [comment] 2022-11-18 10:34
I'll close it as a duplicate of #2373, please track it there. Thanks

**Closed** 2022-11-18 13:46 UTC
Labels: bug, Platform: Android, waiting for feedback, Platform: Java
