### ISSUE TITLE
coroutine support for spring boot !

### ISSUE THREAD

**Issue by iamkdblue** [getsentry/sentry-java#1506] opened 2021-06-01 09:57 UTC
_Platform:_
- [ ]  Spring ->Spring boot v 2.5

_IDE:_
- [ ] IntelliJ IDEA 2021.1.1 (Community Edition)
Build #IC-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Non-Bundled Plugins: com.intellij.ideolog (201.0.22.0), detekt (1.16.0), com.dubreuia (2.2.0), wu.seal.tool.jsontokotlin (3.6.1), in.1ton.idea.spring.assistant.plugin (0.12.0), org.jetbrains.kotlin (211-1.4.32-release-IJ7142.27)
Kotlin: 211-1.4.32-release-IJ7142.27

The version of the SDK:
5.0.0-beta.7

---
I have the following issue:

Sentry not able to send error content inside withContext(Dispatchers.IO) 

cant find SentryContext() and launch in spring boot
and i am using withContext(Dispatchers.IO) not launch , 
using coroutine support library `implementation("io.sentry:sentry-kotlin-extensions:5.0.0-beta.7")`

This issue is not fixed yet but marked as closed! [Issue](https://github.com/getsentry/sentry-java/issues/973)

**Comment by marandaneto** [comment] 2021-06-01 10:06
@iamkdblue thanks for reporting, would you mind to share the code snippet?

```
import io.sentry.kotlin.SentryContext
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

        withContext(SentryContext()) {
            // code
        }

        GlobalScope.launch(SentryContext()) {
            // code
        }
```

works just fine here

**Comment by iamkdblue** [comment] 2021-06-01 10:40
Thanks @marandaneto ,i restarted my intellij and now getting SentryContext() but not getting logs as expected !

I am testing with this endpoint!

```
@GetMapping("/test")
    suspend fun test() {
        try {
            logger.info("Outside withContext")
            Sentry.addBreadcrumb("Sentry breadcrumb1")
            withContext(SentryContext()) {
                val user = User()
                user.email = "test@gmail.com"
                Sentry.setUser(user)
                logger.info("Inside withContext")
                Sentry.addBreadcrumb("Sentry breadcrumb2")
            }
            throw Exception("This is a test.")
        } catch (e: Exception) {
            logger.error("Test exception caught $e")
        }
    }
```
What i am getting now !
![Screenshot 2021-06-01 at 4 07 41 PM](https://user-images.githubusercontent.com/17172841/120309986-81798b80-c2f3-11eb-8d79-03ab0c1bdd04.png)

It should log as given orders, let me know if I am doing anything wrong!
->Outside withContext
->Sentry breadcrumb1
->Inside withContext
->Sentry breadcrumb2

**Comment by marandaneto** [comment] 2021-06-01 11:33
@maciejwalkowiak can you validate that?

If I understood correctly, you need to capture an event inside of `withContext` to log `Inside withContext` and `Sentry breadcrumb2`, if the error happens after the coroutine is over, it won't log anything.

The new context clones the current Scope, which means `withContext` block contains all the data from the previous context but not the other way around

**Comment by iamkdblue** [comment] 2021-06-01 11:38
@marandaneto I updated code snippet, have a look I put error inside withContext, and its not sending logs !

**Comment by marandaneto** [comment] 2021-06-01 11:45
> @marandaneto I updated code snippet, have a look I put error inside withContext, and its not sending logs !

can you just try: `Sentry.captureException(new Exception("This is a test."))` instead of `throw Exception("This is a test.")`?

**Comment by iamkdblue** [comment] 2021-06-01 12:02
Yes,Sentry.captureException(new Exception("This is a test.")) is working as expected !

**Comment by marandaneto** [comment] 2021-06-02 06:14
@iamkdblue I suspect that the Java handler exception somehow captures the event in a different thread instead of the coroutines one, @maciejwalkowiak mind having a look if it's in our end or that's how coroutines operate and we can't do much?

**Comment by maciejwalkowiak** [comment] 2021-06-07 14:01
@iamkdblue context created in child coroutine is not propagated back to the original coroutine. This is by design and I don't think there is anything we can do about it. MDC in [Slf4j integration](https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-slf4j) works exactly the same:

Running:
```java
suspend fun test() {
    try {
      MDC.put("xxx", "1")
      logger.info("Outside withContext {}", MDC.get("xxx"));
      MDC.put("xxx", "2")
      withContext(MDCContext()) {
        MDC.put("xxx", "3")
        logger.info("Inside withContext {}", MDC.get("xxx"))
        MDC.put("xxx", "4")
        logger.info("Inside withContext2 {}", MDC.get("xxx"))
        throw Exception("This is a test.")
      }
    } catch (e: Exception) {
      logger.error("Test exception caught $e {}", MDC.get("xxx"))
    }
  }
```

Gives output:

```
Outside withContext 1
Inside withContext 3
Inside withContext2 4
Test exception caught java.lang.Exception: This is a test. 2
```

**Comment by marandaneto** [comment] 2021-06-07 14:22
@maciejwalkowiak if you remove the try/catch, and run the code with the `SentryContext` instead, does the `throw Exception` get reported by Sentry uncaught exception handler with the correct values? I just want to be sure that this is correct.

**Comment by maciejwalkowiak** [comment] 2021-06-08 09:14
With Spring MVC it does have correct values, but coroutines are used usually with Spring Webflux for which we do not have yet the uncaught exception handler.

**Comment by marandaneto** [comment] 2021-06-08 09:33
ok sounds like this is going to be tracked on #640 then, hence we can close this as the coroutines integration works as intended.

**Closed by marandaneto** 2021-06-08 09:33 UTC
Labels: waiting for feedback
