### ISSUE TITLE
Scope.getSpan() may return a transaction that has already been finished

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-java#1207] opened 2021-01-25 18:35 UTC
https://github.com/getsentry/sentry-java/blob/db14f634725c5d0c7d644392bbe4b79d46144166/sentry/src/main/java/io/sentry/Scope.java#L116-L132

From the looks of it, this code may return a transaction that has already been `finish()`'ed and sent to Sentry. As far as I can tell, there's not much value in returning a transaction that cannot be used anymore, so perhaps it should return `null` in this case too?

I'm not sure whether this is expected or what's the best solution to this.

Looking through TS and Python implementation, it looks like their version of `getSpan()` simply returns the span set by the user on the scope, without any logic whatsoever (no filtering by active/inactive).

cc @bruno-garcia

**Comment by Tyrrrz** [comment] 2021-01-25 18:37
Nevermind, looks like this code resets the transaction on the scope after it finishes.

https://github.com/getsentry/sentry-java/blob/db14f634725c5d0c7d644392bbe4b79d46144166/sentry/src/main/java/io/sentry/Hub.java#L551-L555

So, in effect, `scope.getSpan()` will never return a non-active transaction. Is my understanding correct? @maciejwalkowiak @marandaneto

**Comment by marandaneto** [comment] 2021-01-26 07:38
I'd say so, as the code snippet calls `getLatestActiveSpan`:

https://github.com/getsentry/sentry-java/blob/c002817958677ee8cbfabbaca93e60f67d5e2480/sentry/src/main/java/io/sentry/SentryTransaction.java#L250-L262

looks like it cannot return nonfinished spans, @maciejwalkowiak to confirm but it's pretty much that, so closing it.

**Closed by marandaneto** 2021-01-26 07:38 UTC
Labels: performance

**Comment by maciejwalkowiak** [comment] 2021-01-26 14:17
Confirmed.
