### ISSUE TITLE
Don't report server_name on Android

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1396] opened 2021-04-13 21:19 UTC
![image](https://user-images.githubusercontent.com/1633368/114622768-663bb980-9c7c-11eb-839d-bcb43e8a4b40.png)

**Comment by marandaneto** [comment] 2021-04-13 21:59
this happens because `options.isAttachServerName()` is enabled by default, we need to disable it for Android.

**Comment by bruno-garcia** [comment] 2021-04-13 23:25
![image](https://user-images.githubusercontent.com/1633368/114633074-e880a980-9c8d-11eb-8658-1cf23ce75984.png)

![image](https://user-images.githubusercontent.com/1633368/114633097-f0404e00-9c8d-11eb-95de-6e6a9838617a.png)


😄

**Comment by bruno-garcia** [comment] 2021-04-13 23:38
It's actually already set:

https://github.com/getsentry/sentry-java/blob/4bc43535b91c5bfabc17861b8e24caa47623c23d/sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java#L90

I vaguely recall discussing this in the PR so we wouldn't add it on Android. Now I'm not sure what SDK version I got that screenshot from. Maybe it was an old one and we can just close the SDK.

**Comment by marandaneto** [comment] 2021-04-14 07:03
indeed https://github.com/getsentry/sentry-java/pull/1146#issuecomment-754631090
the thing is, it's been disabled by Android since the start.

it'd also set the `event.serverName` if one enables `options.enableExternalConfiguration` or setting a value to `options.serverName` so both things would be done manually by the user, not automatically, hence not a bug.

I ran it and it does not automatically set the `serverName` for Android by default, so closing it.

**Closed by marandaneto** 2021-04-14 07:03 UTC
Labels: Android
