### ISSUE TITLE
Add extra to UserInterface

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-java#425] opened 2017-06-21 11:58 UTC
The UserInterface should also provide a `extra` property for arbitrary data.
https://github.com/getsentry/react-native-sentry/issues/67

**Comment by bretthoerner** [comment] 2017-06-21 19:18
Yeah I need to add this, I think this is a dupe of #336 so I'm going to close this one.

Since a few people have asked recently I'll try to get to it this week.

**Closed by bretthoerner** 2017-06-21 19:18 UTC
