### ISSUE TITLE
Sentry init is causing ANR

### ISSUE THREAD

**Issue by filipatbnp** [getsentry/sentry-java#2749] opened 2023-05-30 18:21 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.1

### Proguard

Enabled

### Version

5.7.3

### Steps to Reproduce

I have app configured like so https://docs.sentry.io/platforms/android/configuration/manual-init/ (default disabled i manifest, init in appliaction's onCreate)

### Expected Result

no ANR

### Actual Result

I have ANR's on production version of the application, the rate is (last 60 days) affected users: 24

```
...(native stuff)
at java.lang.Runtime.nativeLoad (Native method)
at java.lang.Runtime.nativeLoad (Runtime.java:1121)
at java.lang.Runtime.loadLibrary0 (Runtime.java:1075)
at java.lang.Runtime.loadLibrary0 (Runtime.java:998)
at java.lang.System.loadLibrary (System.java:1661)
at io.sentry.android.ndk.SentryNdk.<clinit> (SentryNdk.java:19)
at java.lang.Class.classForName (Native method)
at java.lang.Class.forName (Class.java:454)
at java.lang.Class.forName (Class.java:379)
at io.sentry.android.core.LoadClass.loadClass (LoadClass.java:21)
at io.sentry.android.core.AndroidOptionsInitializer.installDefaultIntegrations (AndroidOptionsInitializer.java:167)
at io.sentry.android.core.AndroidOptionsInitializer.init (AndroidOptionsInitializer.java:133)
at io.sentry.android.core.AndroidOptionsInitializer.init (AndroidOptionsInitializer.java:86)
at io.sentry.android.core.AndroidOptionsInitializer.init (AndroidOptionsInitializer.java:66)
at io.sentry.android.core.SentryAndroid.lambda$init$1 (SentryAndroid.java:92)
at io.sentry.Sentry.init (Sentry.java:116)
at io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:83)
at io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:64)
at pl.bnp.gomobile.di.sentry.SentryLoggerImpl.init (SentryLoggerImpl.kt:52)
at my.app.MyApplication.onCreate (MyApplication.kt:101)
```

**Comment by filipatbnp** [comment] 2023-05-30 18:22
similar to #1862

**Comment by romtsn** [comment] 2023-05-30 18:41
@filipatbnp have you tried updating to the latest version of the SDK? 5.7.3 is more than a year old, perhaps we've made some improvements there

**Comment by markushi** [comment] 2023-06-07 13:42
@filipatbnp any chance you had a look at this?

**Comment by stefanosiano** [comment] 2023-06-14 15:00
Closing, as it should be resolved in newer versions of the SDK.
Please, reopen it in case the issue isn't fixed by updating to the latest version of the SDK

**Closed as completed by stefanosiano** 2023-06-14 15:00 UTC
Labels: Bug
