### ISSUE TITLE
Crash in SentryFrameMetricsCollector

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-java#2951] opened 2023-09-25 12:33 UTC
### Description

From play console:

```
Exception java.lang.RuntimeException:
  at android.view.DisplayEventReceiver.nativeInit
  at android.view.DisplayEventReceiver.<init> (DisplayEventReceiver.java:63)
  at android.view.Choreographer$FrameDisplayEventReceiver.<init> (Choreographer.java:893)
  at android.view.Choreographer.<init> (Choreographer.java:227)
  at android.view.Choreographer.<init> (Choreographer.java)
  at android.view.Choreographer$1.initialValue (Choreographer.java:111)
  at android.view.Choreographer$1.initialValue (Choreographer.java:106)
  at java.lang.ThreadLocal.setInitialValue (ThreadLocal.java:160)
  at java.lang.ThreadLocal.get (ThreadLocal.java:150)
  at android.view.Choreographer.getInstance (Choreographer.java:266)
  at io.sentry.android.core.internal.util.SentryFrameMetricsCollector.lambda$new$1 (SentryFrameMetricsCollector.java)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
```

**Comment by kahest** [comment] 2023-09-27 13:53
related (duplicate of?): https://github.com/getsentry/sentry-java/issues/2912

**Comment by markushi** [comment] 2023-09-27 13:53
Closing in favor of https://github.com/getsentry/sentry-java/issues/2912

**Closed as not planned by markushi** 2023-09-27 13:53 UTC
