### ISSUE TITLE
DefaultLifecycleObserver Issue

### ISSUE THREAD

**Issue by Blinkq** [getsentry/sentry-java#1553] opened 2021-06-23 12:01 UTC
_Platform:_
Unity 2020.3.12f1 LTS, Android.

_Build system:_
- [ ]  Gradle

_Platform installed with:_
- [ ] Maven Central

The version of the SDK:
**5.0.1**

---
I have the following issue:

When using Android Sentry with Unity 2020, facing error:

```
java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:188)
        at io.sentry.android.core.AppLifecycleIntegration.addObserver(AppLifecycleIntegration.java:92)
        at io.sentry.android.core.AppLifecycleIntegration.register(AppLifecycleIntegration.java:60)
        at io.sentry.Sentry.init(Sentry.java:187)
        at io.sentry.Sentry.init(Sentry.java:116)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:59)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:32)
        at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:27)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2411)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2381)
        at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:44)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7618)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7097)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6970)
        at android.app.ActivityThread.access$1500(ActivityThread.java:255)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8047)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Works well on 2019 and 2018.

Please, take a look at this article : https://stackoverflow.com/questions/59067743/what-is-this-error-and-why-this-doesnt-happen-when-i-dont-use-library-like-a-c

**Steps to reproduce:**
- Download Unity 2020LTS
- Import through Package Manager ExternalDependenciesResolver
- Create SentryDependecies.xml in Editor folder

```
<dependencies>
  <androidPackages>
    <androidPackage spec="io.sentry:sentry-android:5.0.1">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```

-Resolve Android Libraries
-Create AndroidManifest in Plugins/Android and add Sentry initialization line

**Actual result:**
- Facing Crash.
`java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"`

**Expected result:**
- Works well

**Comment by marandaneto** [comment] 2021-06-23 12:10
@Blinkq thanks for raising this, which version of `androidx.lifecycle:lifecycle-process` are you using? It's a `default` method, it should not be an issue if using not that old versions.

**Comment by Blinkq** [comment] 2021-06-23 14:33
Didnt found process, 
found that lifecycle libs in my project:
-androidx.lifecycle:lifecycle-common-2.0.0
-androidx.lifecycle:lifecycle-livedata-2.0.0
-androidx.lifecycle:lifecycle-livedata-core-2.0.0
-androidx.lifecycle:lifecycle-runtime-2.0.0
-androidx.lifecycle:lifecycle-viewmodel-2.0.0

**Comment by marandaneto** [comment] 2021-06-24 08:03
@Blinkq can you try using 2.2.0? that's the version we use right now and I don't see any issues (its a transitive dependency of sentry).
either Unity or a transitive dependency is doing something fishy with dependency resolution.

**Comment by Blinkq** [comment] 2021-06-27 14:42
@marandaneto was trying with 2.2.0, still same error

**Comment by marandaneto** [comment] 2021-06-28 07:31
@Blinkq could you push a repro case on GH? cus I can't reproduce it in a normal app (non Unity), an empty app that reproduces the issue would be awesome, thanks

**Comment by Blinkq** [comment] 2021-06-28 13:43
Made Android Studio project from Unity, take a look 
https://github.com/Blinkq/sentry_test

**Comment by marandaneto** [comment] 2021-06-29 07:02
@Blinkq this project does not even compile, and I can see that you are not using Gradle's dependency resolution but instead copy/paste the JAR files https://github.com/Blinkq/sentry_test/tree/master/unityLibrary/libs
most of the libraries have transitive dependencies so unless you copy/paste everything correct, it won't work.
for sentry, for example, you are missing a few jars/aars.

`playon-0.2.1` is missing too.

prefer the `implementation` with groupId and artifactId, that downloads dependencies from MavenCentral if necessary.

that said, please make the project compilable/runnable so I can check.

**Comment by Blinkq** [comment] 2021-06-29 07:53
@marandaneto Hello, sorry, .gitignore was ignoring too much, removed it and pushed hole project

**Comment by marandaneto** [comment] 2021-06-29 11:53
@Blinkq please check your project and dependencies, your issue isn't a sentry's issue, you're mixing up transitive dependency versions eg, androidx.lifecycle.lifecycle-viewmodel 2.0.0 and androidx.lifecycle.lifecycle-common 2.2.0, or androidx.arch.core.core-common 2.1.0 and androidx.arch.core.core-runtime 2.0.0, sometimes transitive dependencies should match versions otherwise they can cause issues, that's why using a repository is always better than embedding jars/aars.

I can't debug the issue because I'd have to fix all of those conflicts, please use Gradle dependency resolution instead of jars/aars, except if your libraries are not published on a maven repo, which is not the case for the androidx libs.

**Comment by marandaneto** [comment] 2021-06-29 12:22
if I delete all the androidx jars/aars, comment out all the code that adds the androidx libs, add `android.useAndroidX=true` which is required by AGP, the project compiles and runs.

to init sentry via maven repository:
https://docs.sentry.io/platforms/android/#install

so I'll close it, its more a project setup rather than a bug.

**Closed by marandaneto** 2021-06-29 12:22 UTC
Labels: Android, waiting for feedback

**Comment by Blinkq** [comment] 2021-07-11 20:24
@marandaneto Hello, would like to return to this issue. I managed to build your plugin and add fix that mentioned from stackoverflow. 
I just override all abstract methods from parent "DefaultLifecycleObserver". That helped me and resolved my problem.
```
  @Override
  public void onCreate(@NonNull LifecycleOwner owner) {}

  @Override
  public void onResume(@NonNull LifecycleOwner owner) {}

  @Override
  public void onPause(@NonNull LifecycleOwner owner) {}

  @Override
  public void onDestroy(@NonNull LifecycleOwner owner) {}
```
I made update to project that I shared with you, take a look, I leaved there only your library. That literly empty unity project where I added https://github.com/googlesamples/unity-jar-resolver and <androidPackage spec="io.sentry:sentry-android:5.0.1"> .
This project generate error from my first post, but if you will override all methods, everything will work. I added sentry core library with fix to root, you can try replace original to see that its working.
One more thing that I found, I dont know why, but when changing gradle from current 3.6.0 to 3.4.0 that will work too. And this is the reason why Unity2018 and 2019 working, they are using gradle 3.4.0, while Unity2020 using 3.6.0.

I would like to ask you to add this fix. We are using your library to track errors from our SDK, and we cant move forward without this fix.

**Comment by marandaneto** [comment] 2021-07-13 15:51
@Blinkq I could not reproduce your issue, again:

gradle.properties
`android.useAndroidX=true` is required by AGP, your project does not have it.
`android.enableR8=false` is deprecated, you can comment it out

build.gradle from unity library, you can comment and delete all the jars and aars under the libs folder.
```
    implementation(name: 'androidx.lifecycle.lifecycle-process-2.2.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-runtime-2.2.0', ext:'aar')
    implementation(name: 'io.sentry.sentry-android-5.0.1', ext:'aar')
    implementation(name: 'io.sentry.sentry-android-core-5.0.1', ext:'aar')
    implementation(name: 'io.sentry.sentry-android-ndk-5.0.1', ext:'aar')
```

build.gradle from launcher project, add sentry as a maven dependency that downloads transitive dependencies (androidx, gson, etc...)
```
dependencies {
    ...
    implementation 'io.sentry:sentry-android:5.0.1'
}
```

after doing that in your [sample project](https://github.com/Blinkq/sentry_test), your project builds and runs normally.
so my [comment](https://github.com/getsentry/sentry-java/issues/1553#issuecomment-870552783) is still valid.

**Comment by offline** [comment] 2021-07-14 10:13
We also experience same behavior in Unity2020. The problem is we are an SDK and can't force developers that want to integrate our SDK to change their gradle.properties file. 

For now we used Blinkq's method to solve it, but it means we won't be able to update Sentry without modify the code each time.

**Comment by marandaneto** [comment] 2021-07-14 11:08
the `gradle.properties` changes are not really necessary, its deprecated features, the solution described above also works if they are not set, but triggers warnings by AGP.

**Comment by bramhaag** [comment] 2021-07-30 10:39
[This issue can also be caused by a bug in the latest version of the Android Gradle Plugin under specific circumstances. ](https://issuetracker.google.com/issues/194289155)
