### ISSUE TITLE
Sentry Invalidating Transactions for unfinished Spans

### ISSUE THREAD

**Issue by kylannjohnson** [getsentry/sentry-java#3222] opened 2024-02-22 19:26 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.2.2

### Proguard

Enabled

### Version

7.3.0

### Steps to Reproduce

Start a transaction and hold a reference to it.  I've seen both scoped and non-scoped transactions have the effect, but I think scoped transaction are more likely.  With that transaction, start a child span, but don't finish it.   Finish the transaction.

### Expected Result

I would expect the child spans to be stopped when the transaction stops.  Their span status should probably be SpanStatus.ABORTED.

### Actual Result

If we query our project metrics from the statsV2 endpoint, there are a very high number of invalid_transaction. 

In 24 hours, here are the results of the [Stats V2 endpoint](https://docs.sentry.io/api/organizations/retrieve-event-counts-for-an-organization-v2/)

```
Outcome           Reason
accepted          none                   :  3356853
client_discard    cache_overflow         :  184
client_discard    sample_rate            :  704095
client_discard    network_error          :  50311
client_discard    queue_overflow         :  23
invalid           invalid_transaction    :  1893851
```

If the following code is used as the tracing callback, a coworker who experienced lost transactions was able to see them.

```kotlin
beforeSendTransaction = SentryOptions.BeforeSendTransactionCallback { transaction, _ ->
        
     val finishedVsUnfinishedSpans = transaction.spans.partition { it.isFinished }

     if (finishedVsUnfinishedSpans.second.isNotEmpty()) {
        with(transaction) {
              spans.clear()
              spans.addAll(finishedVsUnfinishedSpans.first)
        }
     }

     transaction
 }
```

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2113) by [Unito](https://www.unito.io)

**Comment by iker-barriocanal** [comment] 2024-02-26 12:23
Thanks for reporting, @kylannjohnson! The root cause is a regression in Relay and should be fixed in https://github.com/getsentry/relay/pull/3162. I'll keep this issue updated when Relay is fixed and deployed.

**Closed** 2024-02-27 08:45 UTC
Labels: Type: Bug, Platform: Android, Platform: Java, Sync: Jira

**Comment by iker-barriocanal** [comment] 2024-02-27 16:19
The fix should already be in production since ~15:00 UTC. Let me know or reopen the issue if this is still happening.

**Comment by kylannjohnson** [comment] 2024-03-04 15:49
Thanks @iker-barriocanal .  I retested our scenario here and it does appear to be improved.  I'll keep monitoring to make sure the problem is gone. Thanks again!
