### ISSUE TITLE
The event in the cache dir is not sent to the sentry server when the sentry-java sdk reconnects to the sentry service

### ISSUE THREAD

**Issue by gaojun2048** [getsentry/sentry-java#1612] opened 2021-07-21 06:21 UTC
Hi ,
My sentry server version is 21.6.1 and my sentry-java sdk version is 5.0.1.
My test code like this:

```
SentryOptions options = new SentryOptions();
options.setDsn(NoticeConfig.STREAMING_SENTRY_DSN);
HashMap<String, String> map = getEnterpriseCodeAndVersion();
options.setEnvironment(map.get(ARK_ENTERPRISE_CODE));
options.setRelease(map.get(ARK_VERSION));

//设置缓存相关配置
options.setCacheDirPath("/opt/soft/log/sentry_cache_arknotice");
options.setMaxCacheItems(3);
options.setFlushTimeoutMillis(10000);
options.setEnableScopeSync(true);
options.setMaxQueueSize(1);
options.setEnableShutdownHook(true);
options.isDebug();
Sentry.init(options);
Sentry.isEnabled();
```

When I stop the sentry server , I found some envelope file added to dir `/opt/soft/log/sentry_cache_arknotice`. 

I expected that when I restart the sentry server, the events in the dir `/opt/soft/log/sentry_cache_arknotice` will be sent to the sentry server, but in fact it is not.

What`s wrong with it?

**Comment by bruno-garcia** [comment] 2021-07-21 19:39
The SDK currently only sends what's on disk if something is captured like a session update, transaction or a new issue (message/error) etc. This is also the case on the .NET SDK: https://github.com/getsentry/sentry-dotnet/issues/803

We have an issue already to track adding periodic sending of cached events: #912

Please upvote the issue there to help us prioritize things, I'll close this as a duplicate.

**Comment by AshStefanOltmann** [comment] 2021-07-26 10:30
> The SDK currently only sends what's on disk if something is captured like a session update, transaction or a new issue (message/error) etc.

@bruno-garcia 
Can you please verify that? I found that to be not true!

I set a cache dir, but the envelope files created during offline use won't be send even if I produce a new event.

So even with offline cache set offline crashes seem to be lost forever.

**Comment by marandaneto** [comment] 2021-07-26 15:20
options.addIntegration(
        new SendCachedEnvelopeFireAndForgetIntegration(
            new SendFireAndForgetEnvelopeSender(() -> options.getCacheDirPath())));

Lives in the android module, we have to move it to the sentry module, so it'd work for pure java sdk as well.

**Comment by bruno-garcia** [comment] 2021-07-26 15:53
@marandaneto is that going to send events periodically, if the process goes offline then back online?

**Comment by marandaneto** [comment] 2021-07-26 15:54
No, this issue isn't about sending events periodically, but sending events on restartas it's stated on the issue description.

**Comment by bruno-garcia** [comment] 2021-07-26 15:55
@marandaneto I see #1309 now, the issue detail talks about 'reconnecting' which threw me off. 
It's anyway a dupe of #1309 and perhaps also #912 (based on the title)

**Comment by AshStefanOltmann** [comment] 2021-07-27 07:16
> options.addIntegration(
> new SendCachedEnvelopeFireAndForgetIntegration(
> new SendFireAndForgetEnvelopeSender(() -> options.getCacheDirPath())));
> 
> Lives in the android module, we have to move it to the sentry module, so it'd work for pure java sdk as well.

Thank you, that works for me as expected. 👍 

I also would expect that I don't need to configure that extra after setting the cacheDir, but this automatically happens when a cacheDir was set.

I guess @gaojun2048 expected the same.

Maybe you find a solution to set the cacheDir also to a default value like LOCALAPPDATA on Windows or the Library/Caches/ dir on macOS. Would make sense to me that offline caching is enabled per default.

**Comment by marandaneto** [comment] 2021-07-27 08:59
> I also would expect that I don't need to configure that extra after setting the cacheDir, but this automatically happens when a cacheDir was set.

@AshStefanOltmann yep, that would be a fix, its an oversight.

> Maybe you find a solution to set the cacheDir also to a default value like LOCALAPPDATA on Windows or the Library/Caches/ dir on macOS. Would make sense to me that offline caching is enabled per default.

that's arguable since offline caching has some cost (IO) etc, I'd prefer to be opt-in for the server-side which rarely runs out of connection, but that would be a conversation for another issue.

**Comment by marandaneto** [comment] 2021-07-27 09:00
not sure if I tag as a `bug` or `enhancement` since https://github.com/getsentry/sentry-java/issues/1309 is the original issue on how to do it

**Comment by AshStefanOltmann** [comment] 2021-07-27 17:14
@marandaneto There is still a problem with the solution somehow.

If that integration is set it seems that crash reports don't get send if the software is online but only on restart.

What I need is sending the crash report if online (normal case) but caching and not loosing it if the user should be offline.

How can I achieve / workaround that for now?

**Comment by marandaneto** [comment] 2021-07-27 19:17
@AshStefanOltmann if what you say is the actual behavior, it's a bug and we have to fix it.

@maciejwalkowiak mind checking it out?

**Comment by AshStefanOltmann** [comment] 2021-07-28 06:40
@marandaneto Ok, I was wrong here.

In my case debug reveals that "payload reached its size limit". Sorry about that.

That I can create messages that are too big may be a problem for another issue.

**Comment by marandaneto** [comment] 2021-07-28 06:49
@AshStefanOltmann indeed, See https://develop.sentry.dev/sdk/envelopes/#size-limits
consider using the attachments feature maybe, thanks for figuring it out

**Comment by AshStefanOltmann** [comment] 2021-07-28 06:53
@marandaneto Thanks for the hint to the attachment feature. I will try that out.

Are the numbers in the docs are up to date?
My debug log said that 200 kb is the limit and my envelope was above that.

**Comment by marandaneto** [comment] 2021-07-28 07:47
@AshStefanOltmann I believe the size was increased a while ago and logs might be outdated, would you be so nice as to copy-paste the error message? so I can fix it, thanks.

**Comment by AshStefanOltmann** [comment] 2021-07-28 09:45
@marandaneto All good. I may have mistaken that also. I was sure the message from the server said something about 200kb, but if I try to reproduce it's not mentioned anymore. 

Looks good to me.

```
ERROR: Request failed, API returned 413
ERROR: {"detail":"failed to read request body","causes":["payload reached its size limit"]}
ERROR: The transport failed to send the envelope with response code 413
ERROR: Envelope submission failed 
 java.lang.IllegalStateException: The transport failed to send the envelope with response code 413
java.lang.IllegalStateException: The transport failed to send the envelope with response code 413
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:220)
	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by gaojun2048** [comment] 2021-08-03 02:28
Thanks everyone, I will try @marandaneto solution and submit a report.

**Comment by gaojun2048** [comment] 2021-08-13 09:03
Today I try @marandaneto solution and it works fine. Thank you

**Closed** 2021-08-13 09:03 UTC
Labels: enhancement
