### ISSUE TITLE
Sentry does not work with spring boot, logback and native compilation to graalvm

### ISSUE THREAD

**Issue by hadson172** [getsentry/sentry-java#2954] opened 2023-09-26 06:39 UTC
### Integration

sentry

### Java Version

17

### Version

6.29.0

### Steps to Reproduce

My logback config:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml" />
    <springProperty scope="context" name="name" source="spring.application.name"/>
    
</configuration>
```

and dependnecies:

```
    implementation("io.sentry:sentry-spring-boot-starter-jakarta:6.29.0")
    implementation("io.sentry:sentry-logback:6.29.0")
```

### Expected Result

Errors are sent to the sentry.

### Actual Result
When developing on JVM (localhost) everything work fine, error are sent to the sentry.
When deployed on production it does not send any error to sentry. There is no error in the console. 
I have similar issue in different libararies and all what it has to be done was to add some reflection accessed classes to graalvm config files. When it comes to sentry it seems that adding SentryAppender:class is not enough. Any advices?

**Comment by lbloder** [comment] 2023-09-26 10:05
Hello @hadson172,
Thanks for reaching out to us.

I tried to reproduce your issue, but unfortunately wasn't able to. Works without adding anything to the graalvm config.
Could you provide some additional information in order to help us track down the issue?

Which errors are not sent to Sentry? Error-level logs from `logback` or errors directly captured through `Sentry.captureException()` ? How do you configure sentry? In the `logback.xml` or through `application.properties`?

Also, for the `SentryAppender` to work it needs to be configured in `logback.xml`, you can find an example configuration in the Sentry docs [here](https://docs.sentry.io/platforms/java/guides/logback/#configure). If you have configured your dsn through the spring configuration (`application.properties`), then you don't need to add it to the logback configuration.

Are there any differences between your `local` and `production` configuration?

**Comment by hadson172** [comment] 2023-09-26 16:32
Hi @lbloder 
My logging config is taken from this tutorial - https://spring.io/blog/2022/10/12/observability-with-spring-boot-3
So its mix of logback and spring autoconfiguration.

> Which errors are not sent to Sentry? Error-level logs from logback or errors directly captured through Sentry.captureException()

Both unhandled exceptions, handled exceptions and logger.error(...) are sent on localhost (bootRun) but not with nativeCompile

> How do you configure sentry? In the logback.xml or through application.properti

I use autoconfiguration (so non of properties are set in .properties file except `sentry.enviroment`) and I pass DSN env variable.

`Are there any differences between your local and production configuration?`

Only difference is bootRun vs nativeCompile

Even when i run debug mode in application.properties initi data is printed on startup (for localhost) but not for nativeCompile

**Comment by lbloder** [comment] 2023-09-26 18:48
Hi @hadson172,
Thank you for your detailed description. Based on the Spring docs [here](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.introducing-graalvm-native-images.understanding-aot-processing), I do have a hunch.

Since you pass the sentry dsn as an environment variable, I'm guessing that it's not set during build time. Which would mean, that the sentry hub won't be instantiated and thus won't be part of the native build.

I'll test my theory in the next few hours and come back to you.

There are two things you could try:
1) Set a dsn in your environment during build and see if that works as expected.
2) Set the dsn in application.properties.

Hope this helps.

**Comment by hadson172** [comment] 2023-09-26 20:04
**Edit: I wrote the post below before your answer but forgot to submit it.**

Hosting is fly.io and lang is kotlin if this may help somehow.

Seems that if I initialize it by hand like this:

![obraz](https://github.com/getsentry/sentry-java/assets/8881977/d968bad4-ce40-4785-b48d-7017635721b7)


It is working. Any ideas why ?

**Comment by hadson172** [comment] 2023-09-26 20:17
And from what i seeing you probably right with this because when i set something like this:
`sentry.dsn=${SENTRY_DSN}` in application.properties, my app is not able to resolve this dsn. (so i must be doing something on build time).

Infrastructure is fly.io so I am just dropping docker image so setting variable on build time could be little bit problem.

So this workaround for java client work find but any ideas how to setup logback integration ?

**Comment by lbloder** [comment] 2023-09-26 22:28
Yeah, what it does at build time is checking whether a dsn is set (it doesn't care about the actual value of the dsn, just that it is set), to decide if Sentry should be initialized (`@ConditionalOnProperty` is evaluated at build time)

Here's how It worked for my build:
- Set `sentry.dsn=${SENTRY_DSN}` in `application.properties` 
- In Terminal set the SENTRY_DSN env var to anything (e.g. `export SENTRY_DSN=placeholder`)
- Run gradle native build (`./gradlew nativeCompile` or, if you're building a docker image `./gradlew bootBuildImage`)
- Now you can run the native executable and supply it with the real dsn (e.g.  `SENTRY_DSN=YOUR_REAL_DSN EXECUTABLE`)

The same works for a docker image by passing the SENTRY_DSN like this: `docker run --env SENTRY_DSN=YOUR_DSN YOUR_DOCKER_IMAGE`

Can you give this a try?

**Comment by lbloder** [comment] 2023-09-26 22:30
For logback you can do environment variable substitution in `logback.xml`.
For that you need to configure the `SentryAppender` in `logback.xml` like below:

```
    <appender name="Sentry" class="io.sentry.logback.SentryAppender">
        <options>
            <dsn>${SENTRY_DSN}</dsn>
            <debug>true</debug>
        </options>
    </appender>
```

**Comment by lbloder** [comment] 2023-09-27 06:34
> Yeah, what it does at build time is checking whether a dsn is set (it doesn't care about the actual value of the dsn, just that it is set), to decide if Sentry should be initialized (`@ConditionalOnProperty` is evaluated at build time)
> 
> Here's how It worked for my build:
> 
> * Set `sentry.dsn=${SENTRY_DSN}` in `application.properties`
> * In Terminal set the SENTRY_DSN env var to anything (e.g. `export SENTRY_DSN=placeholder`)
> * Run gradle native build (`./gradlew nativeCompile` or, if you're building a docker image `./gradlew bootBuildImage`)
> * Now you can run the native executable and supply it with the real dsn (e.g.  `SENTRY_DSN=YOUR_REAL_DSN EXECUTABLE`)
> 
> The same works for a docker image by passing the SENTRY_DSN like this: `docker run --env SENTRY_DSN=YOUR_DSN YOUR_DOCKER_IMAGE`
> 
> Can you give this a try?

Hi @hadson172,
So, I did some more testing, and  while the steps above work, there's actually an easier way to do this.
You don't need to change anything in `application.properties` (i.e. leave the dsn out completely as you did originally)
Then you can pass the placeholder (literally "placeholder") as argument to the build:
`./gradlew -Dsentry.dsn=placeholder nativeCompile` or for the docker image `./gradlew -Dsentry.dsn=placeholder bootBuildImage`

Then you can use your environment variable just like before (e.g. `SENTRY_DSN=YOUR_REAL_DSN EXECUTABLE`) or in docker pass it to docker run or set it in a docker-compose file.

Could you try this and let us know if that solved you problem?

**Comment by hadson172** [comment] 2023-09-27 12:29
Perfect,
It appears that setting the ENV variable inside the Dockerfile has successfully resolved all the issues, and the system is now functioning correctly. I appreciate your assistance.

**Comment by adinauer** [comment] 2023-10-02 07:49
Closing this now, as it seems resolved. Please let us know if you need any more help.

**Closed by adinauer** 2023-10-02 07:49 UTC
Labels: Type: Bug, Platform: Java, Waiting for: Product Owner
