### ISSUE TITLE
ApplicationNotResponding

### ISSUE THREAD

**Issue by ukevgen** [getsentry/sentry-java#3428] opened 2024-05-16 10:46 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.7.0

### Proguard

Enabled

### Version

7.0.0

### Steps to Reproduce

Run the application 

### Expected Result

Running apllication without ANR

### Actual Result

ApplicationNotResponding
Background ANR
jdk.internal.misc.Unsafe in park
java.util.concurrent.locks.LockSupport in parkNanos at line 252
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject in awaitNanos at line 1672
java.util.concurrent.ThreadPoolExecutor in awaitTermination at line 1471
io.sentry.transport.AsyncHttpTransport in close at line 157
io.sentry.SentryClient in close at line 910
io.sentry.Hub in close at line 360
io.sentry.Sentry in init at line 223
io.sentry.Sentry in init at line 148
io.sentry.android.core.SentryAndroid in init at line 89
io.sentry.android.core.SentryAndroid in init at line 70

**Comment by stefanosiano** [comment] 2024-05-22 12:46
hi @ukevgen 
From the log it looks like you are initializing the SDK twice. This ANR was [fixed](https://github.com/getsentry/sentry-java/pull/3200) in version 7.4.0 of the Android SDK.
If the issue is not fixed by updating the SDK, feel free to reopen this issue.

**Closed by stefanosiano** 2024-05-22 12:46 UTC
Labels: Type: Bug, Platform: Android, Platform: Java, Waiting for: Product Owner
