### ISSUE TITLE
Sentry.init() causes ANR

### ISSUE THREAD

**Issue by kylannjohnson** [getsentry/sentry-java#2941] opened 2023-09-19 23:24 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.1.0

### Proguard

Enabled

### Version

6.26.0

### Steps to Reproduce

Call Sentry.init() in the onCreate method of the Application class, [per the docs](https://docs.sentry.io/platforms/android/configuration/manual-init/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#manual-initialization)

### Expected Result

For construction of a No-op, you would expect no hit to performance and thus no chance of ANR.

### Actual Result

I replaced our app-specifc paths in the ANR stack trace below.  It looks like the ANR is happening on construction of the NoOp Hub

```
io.sentry.android.core.ApplicationNotResponding: Background ANR
    at io.sentry.JsonSerializer.<init>(unavailable:0)
    at io.sentry.JsonSerializer.<init>(unavailable:71)
    at io.sentry.SentryOptions.<init>(SourceFile:116)
    at io.sentry.SentryOptions.empty(unavailable:0)
    at io.sentry.NoOpHub.<init>(unavailable:0)
    at io.sentry.NoOpHub.<init>(unavailable:14)
    at io.sentry.NoOpHub.<clinit>(unavailable:0)
    at io.sentry.NoOpHub.getInstance(unavailable:0)
    at io.sentry.Sentry.<clinit>(unavailable:0)
    at io.sentry.Sentry.<clinit>(unavailable:40)
    at io.sentry.Sentry.init(unavailable:0)
    at io.sentry.android.core.SentryAndroid.init(unavailable:89)
    at io.sentry.android.core.SentryAndroid.init(unavailable:0)
    at app.foo.crashreporter.sentry.SentryModule$sentryThirdPartyInitialization$1.initialize(unavailable:0)
    at app.foo.crashreporter.sentry.SentryModule$sentryThirdPartyInitialization$1.initialize(unavailable:55)
    at app.foo.init.DomainThirdPartyInitializer.initialize(unavailable:0)
    at app.foo.init.DomainThirdPartyInitializer.initialize(unavailable:51)
    at app.foo.FooApplication.onCreate(unavailable:282)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by romtsn** [comment] 2023-09-21 09:00
Hi @kylannjohnson thanks for reporting. I assume you have disabled auto-init following the docs instructions, right?

```xml
<application>
    <meta-data android:name="io.sentry.auto-init" android:value="false" />
</application>
```

I also, think this is probably a dupe of #2541, let me know if it isn't. Otherwise I'd track it there

**Comment by romtsn** [comment] 2023-09-21 19:20
> > Hi @kylannjohnson thanks for reporting. I assume you have disabled auto-init following the docs instructions, right?
> > ```
> > <application>
> >     <meta-data android:name="io.sentry.auto-init" android:value="false" />
> > </application>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also, think this is probably a dupe of #2541, let me know if it isn't. Otherwise I'd track it there
> 
> Hey @romtsn . Yes on both counts: we turn off auto init and I think that the issue is the eager initialization. Thanks for pointing me to the existing issue.

alright, i'm gonna close this one then, let's track it there. We'll try to find resources and fix that shortly. thanks!

**Closed by romtsn** 2023-09-21 19:20 UTC
Labels: Type: Bug, Platform: Android, Waiting for: Product Owner
