### ISSUE TITLE
Deadlock on startup with log4j

### ISSUE THREAD

**Issue by buckett** [getsentry/sentry-java#660] opened 2019-01-11 13:04 UTC
We recently had Tomcat fail to startup correctly and this look to be because of a deadlock in the log4j/sentry startup. A thread dump shows 2 threads which have got stuck:
````
"ajp-nio-10.1.20.92-8009-exec-2": waiting to acquire [0x0000000702f75e60], holding [0x00000007021114b8, 0x000000070008e230, 0x00000007138c4210]
	at io.sentry.Sentry.getStoredClient(Sentry.java:99)
	at io.sentry.log4j.SentryAppender.createEventBuilder(SentryAppender.java:131)
	at io.sentry.log4j.SentryAppender.append(SentryAppender.java:84)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.apache.juli.logging.impl.Log4JLogger.error(Log4JLogger.java:229)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:750)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
        [...snipped...]
````
and
````
"ajp-nio-10.1.20.92-8009-exec-1": waiting to acquire [0x000000070008e230], holding [0x0000000702f75e60, 0x00000007144e6060]
	at org.apache.log4j.Category.callAppenders(Category.java:204)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:401)
	at io.sentry.DefaultSentryClientFactory.getInAppFrames(DefaultSentryClientFactory.java:524)
	at io.sentry.DefaultSentryClientFactory.createMarshaller(DefaultSentryClientFactory.java:468)
	at io.sentry.DefaultSentryClientFactory.createHttpConnection(DefaultSentryClientFactory.java:427)
	at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:327)
	at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:236)
	at uk.ac.ox.it.sentry.DockerSentryClientFactory.createSentryClient(DockerSentryClientFactory.java:34)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64)
	at io.sentry.Sentry.init(Sentry.java:81)
	at io.sentry.Sentry.init(Sentry.java:44)
	at io.sentry.Sentry.getStoredClient(Sentry.java:102)
	at io.sentry.servlet.SentryServletRequestListener.requestDestroyed(SentryServletRequestListener.java:32)
	at org.apache.catalina.core.StandardContext.fireRequestDestroyEvent(StandardContext.java:6021)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:182)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:479)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
````
Each thread is waiting on the lock held by the other but holding the lock the other thread needs.

**Comment by bretthoerner** [comment] 2019-02-04 18:11
What version of `sentry-java`?

**Comment by joshrosen-stripe** [comment] 2019-05-14 01:29
I think this problem is caused by a bad interaction between Log4J 1.x's global lock, the [`Sentry.synchronized` call in `getStoredClient`](https://github.com/getsentry/sentry-java/blob/4b810150969108429bbb36d28227cb128b986aa0/sentry/src/main/java/io/sentry/Sentry.java#L98), and lazy initialization of Sentry.

I think this deadlock cycle could be broken by either

- Modifying the code to move the body of the `append()` call into a separate thread, thereby moving it out of the Log4J lock.
- Configure Sentry's Log4J appender as an AsyncAppender (effectively doing ⬆️ without code changes).
- Eagerly initialize Sentry prior to the first logging call in the application.
  - If you control your application's source code then you might be able to put a dummy call to `Sentry.getStoredClient()` at the start of your application's `main()` method. That approach won't work for Log4J-configuration-only approaches (e.g. for third-party applications that you don't want to recompile). Instead, perhaps `sentry-log4j` could perform the initialization 
  - Perhaps this could be done in the appender's constructor? Or in a static initializer? I need to think about this a bit more to figure out whether those approaches are free of the same deadlock potential.

It may also be a good idea to figure out whether this deadlock can occur in Log4J-only integrations or whether it's only possible when `sentry-log4j` is mixed with other integration types (such as the `SentryServletRequestListener` appearing in this issue).

**Comment by maciejwalkowiak** [comment] 2020-10-01 10:10
This issue should not occur anymore in Java SDK 3.0. If it happens please comment on this issue.

**Closed by maciejwalkowiak** 2020-10-01 10:10 UTC
