### ISSUE TITLE
Send integrations list as metadata

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-java#1989] opened 2022-04-13 15:10 UTC
### Problem Statement

Right now we only send the sdk packages but not integrations

### Solution Brainstorm

https://github.com/getsentry/sentry-java/blob/74deb437ab935543aff1e0b27c8bb63e60cb86cc/sentry/src/main/java/io/sentry/protocol/SdkVersion.java#L47-L54

So we can learn about the usages of our integrations

**Comment by romtsn** [comment] 2022-04-13 20:47
Dupe of #1885?

**Closed** 2022-04-14 04:18 UTC
Labels: Platform: Android, Platform: Java
