### ISSUE TITLE
Post request body is not getting captured

### ISSUE THREAD

**Issue by krishnakanth23** [getsentry/sentry-java#566] opened 2018-03-13 14:29 UTC
Hi 

I am using sentry in spring boot application. I am able to get url, user, server_name etc details for both GET and POST requests. But in POST request, body is not getting captured.

Is there any way to capture request body? Here our request body is of type JSON.

Any leads on this will be very helpful. Thanks in advance.

**Comment by bretthoerner** [comment] 2018-03-13 14:37
I think this is the same as: https://github.com/getsentry/sentry-java/issues/331

**Comment by bruno-garcia** [comment] 2019-07-15 11:41
Dupe of #331

**Closed by bruno-garcia** 2019-07-15 11:41 UTC
