### ISSUE TITLE
"java.lang.IllegalArgumentException: DSN is required" when trying to run Android instrumentation tests

### ISSUE THREAD

**Issue by alvindizon** [getsentry/sentry-java#1299] opened 2021-02-28 03:38 UTC
We're trying to build UI tests for our Android app, and we're using Android's `fragment-testing` library in order to test Fragments in isolation. However, when we run our tests, the app crashes and viewing logcat, we see the following error: 

```
2021-02-28 11:28:42.706 6222-6222/com.someapp.ui.test E/AndroidJUnitRunner: An unhandled exception was thrown by the app.
2021-02-28 11:28:42.710 6222-6222/com.someapp.ui.test E/InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
2021-02-28 11:28:42.714 6222-6222/com.someapp.ui.test E/MonitoringInstr: Exception encountered by: null. Dumping thread state to outputs and pining for the fjords.
    java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
        at io.sentry.Sentry.initConfigurations(Sentry.java:192)
        at io.sentry.Sentry.init(Sentry.java:162)
        at io.sentry.Sentry.init(Sentry.java:110)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:59)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:32)
        at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:25)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:42)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-02-28 11:28:42.719 6222-6222/? E/THREAD_STATE:   Thread[FinalizerWatchdogDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:442)
        java.lang.Object.wait(Object.java:568)
        java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:341)
        java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:321)
        java.lang.Daemons$Daemon.run(Daemons.java:139)
        java.lang.Thread.run(Thread.java:923)
    
      Thread[HeapTaskDaemon,5,system]
    
      Thread[Binder:6222_2,5,main]
    
      Thread[SentryHostnameCache-0,5,main]
        sun.misc.Unsafe.park(Native Method)
        java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
        java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
        java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        java.lang.Thread.run(Thread.java:923)
    
      Thread[FinalizerDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:442)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
        java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
        java.lang.Daemons$Daemon.run(Daemons.java:139)
        java.lang.Thread.run(Thread.java:923)
    
      Thread[Binder:6222_1,5,main]
    
      Thread[Signal Catcher,10,system]
    
      Thread[Jit thread pool worker thread 0,5,system]
    
      Thread[ReferenceQueueDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:442)
        java.lang.Object.wait(Object.java:568)
        java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
        java.lang.Daemons$Daemon.run(Daemons.java:139)
        java.lang.Thread.run(Thread.java:923)
    
      Thread[main,5,main]
        dalvik.system.VMStack.getThreadStackTrace(Native Method)
        java.lang.Thread.getStackTrace(Thread.java:1736)
        java.lang.Thread.getAllStackTraces(Thread.java:1812)
        androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:680)
        androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:675)
        androidx.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:669)
        androidx.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:554)
        android.app.ActivityThread.installProvider(ActivityThread.java:7241)
        android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        android.app.ActivityThread.access$1300(ActivityThread.java:237)
        android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        android.os.Handler.dispatchMessage(Handler.java:106)
        android.os.Looper.loop(Looper.java:223)
        android.app.ActivityThread.main(ActivityThread.java:7656)
        java.lang.reflect.Method.invoke(Native Method)
        com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    
      Thread[pool-3-thread-1,5,main]
        android.os.BinderProxy.transactNative(Native Method)
        android.os.BinderProxy.transact(BinderProxy.java:540)
        android.content.ContentProviderProxy.call(ContentProviderNative.java:730)
        android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2769)
        android.provider.Settings$Secure.getStringForUser(Settings.java:5438)
        android.provider.Settings$Secure.getString(Settings.java:5394)
        io.sentry.android.core.DefaultAndroidEventProcessor.getAndroidId(DefaultAndroidEventProcessor.java:864)
        io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:118)
2021-02-28 11:28:42.719 6222-6222/? E/THREAD_STATE:     io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:104)
        io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
        java.util.concurrent.FutureTask.run(FutureTask.java:266)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        java.lang.Thread.run(Thread.java:923)
    
      Thread[Binder:6222_3,5,main]
    
      Thread[Profile Saver,5,system]
2021-02-28 11:28:42.719 6222-6222/? E/MonitoringInstr: Dying now...
```

Our test itself makes use `fragment-testing`, `espresso` and `mockk`. We are modeling after Google's own reference for testing [here](https://github.com/android/architecture-components-samples/blob/main/GithubBrowserSample/app/src/androidTest/java/com/android/example/github/ui/repo/RepoFragmentTest.kt). Here's how we setup our test:

```
@RunWith(AndroidJUnit4::class)
class SomeFragmentTest {

...

    @Before
    fun setUp() {
        MockKAnnotations.init(this)
        context = InstrumentationRegistry.getInstrumentation().context

        val scenario = launchFragmentInContainer(themeResId = R.style.AppTheme_Light) {
            SomeFragment().apply {
                dependency1 = this@SomeFragmentTest.dependency1
                ...
            }
        }

        dataBindingIdlingResourceRule.monitorFragment(scenario)

        scenario.onFragment { fragment ->
            Navigation.setViewNavController(fragment.requireView(), navController)
        }
    }
```

Can you suggest a way to disable Sentry for UI/instrumentation tests?

**Comment by marandaneto** [comment] 2021-02-28 19:23
@alvindizon have you tried to use an empty String for the DSN during Sentry init. when doing tests as the error message says? 

> java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.

**Comment by alvindizon** [comment] 2021-02-28 23:32
Hi, thanks for responding. The fragment class itself doesn't use or interact with Sentry directly--only our Application class initializes Sentry via a wrapper so I don't have an idea (for now) how to do that with the fragment test code.

**Comment by alvindizon** [comment] 2021-03-01 01:44
Here's what I've tried so far, but all of them still resulted in the same error.
1. Tried to initialize Sentry on my fragment test code's `@Before` in this manner:

       SentryAndroid.init(context) { options ->
            options.dsn = ""
        }
2. Used a custom JUnit runner that uses a custom `Application` class, and initialized Sentry with empty DSN:
```
class UITestRunner : AndroidJUnitRunner() {
    override fun newApplication(cl: ClassLoader, className: String, context: Context): Application {
        return super.newApplication(cl, TestApp::class.java.name, context)
    }
}
```
```
class TestApp : Application() {
    override fun onCreate() {
       SentryAndroid.init(context) { options ->
            options.dsn = ""
        }
    }
}
```

In my gradle, used the Junit runner like this: `testInstrumentationRunner "com.someapp.UITestRunner"`

**Comment by marandaneto** [comment] 2021-03-01 08:40
I don't follow the problem @alvindizon

also, I don't follow your code snippets, they don't make much sense if the Sentry SDK is initialized by your App's code, and not your testing code, there are many ways on how to solve that, and all of them fall to testing techniques, eg, wrap the Sentry SDK init and mock/fake it in your testing setup.

if you are using the `auto-init` mode, your instrumentation test could have its own Manifest file so you could set an empty DSN there, or even not initing the Sentry SDK at all by disabling the `auto-init` mode, etc...

See docs about manual init. as well https://docs.sentry.io/platforms/android/usage/advanced-usage/#manual-initialization

I'll close it as it's not a bug unless none of the suggested options work, I'd glad to reopen it, thanks.

**Closed by marandaneto** 2021-03-01 08:40 UTC
Labels: Android, waiting for feedback

**Comment by alvindizon** [comment] 2021-03-01 09:30
Hi @marandaneto, thanks for replying. I think the description is pretty clear; I'm simply reporting what I'm seeing on my end--that an exception from the Sentry SDK appeared in logcat after the app crashed from running the test. It's certainly unexpected and does not make sense to me also 😅 that's what led me to open an issue here and seek advice, in case something similar was already reported. My code snippets show what I've attempted in order to resolve the error as best as I can, and I used testing techniques in all of those code snippets.

If I understood correctly your definition, and looking at the docs you linked, we're not using`auto-init`. As I've described before, we're initializing Sentry via an instance of the  Application class.  I understand why you have to close this ticket though, I'll be happy to update this with a comment if we resolve this. Thanks

**Comment by marandaneto** [comment] 2021-03-01 12:28
@alvindizon yeah I get that, thanks for replying, just trying to point you in the right direction, but it's not an SDK issue as far as I am concerned.

2. btw take a look at https://developer.android.com/training/testing/junit-runner
you don't need to create your own `UITestRunner`

3. you can't mock statics like this, maybe with `mockkStatic`, but I'd not go this route.

good luck :)

**Comment by MRezaNasirloo** [comment] 2021-12-05 12:30
For anyone having this issue

Disable auto init in your `androidTest/AndroidManifest.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <application>
        <meta-data
            android:name="io.sentry.auto-init"
            android:value="false" />
        <!-- OR -->
        <provider
            android:name="io.sentry.android.core.SentryInitProvider"
            android:authorities="${applicationId}.SentryInitProvider"
            tools:node="remove" />
    </application>
</manifest>
```
