### ISSUE TITLE
InternalError: Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by apue** [getsentry/sentry-java#731] opened 2019-06-27 08:00 UTC
I am using sentry on my android application, which helped us a lot, so thanks a lot for your excellent project. However, I found a strange problem:
0. we are using sentry 1.7.3 (from the release notes, I didn't find any fix on this specific problem)
1. I installed the ANRWatchDog in my app (com.github.anrwatchdog:anrwatchdog:1.3.0)
2. in the caught exception handler, we will upload the exception stack trace via sentry
3. in some cases, it will throw a new exception, the stack trace is:

```
InternalError: Thread starting during runtime shutdown
java.lang.Thread in nativeCreate
java.lang.Thread in start at line 730
java.util.concurrent.ThreadPoolExecutor in addWorker at line 941
java.util.concurrent.ThreadPoolExecutor in execute at line 1348
io.sentry.connection.AsyncConnection in send at line 96
io.sentry.connection.BufferedConnection$2 in send at line 193
io.sentry.SentryClient in sendEvent at line 135
io.sentry.SentryClient in sendEvent at line 176
io.sentry.SentryClient in sendException at line 203
io.sentry.Sentry in capture at line 156
com.mycompany.myapp.handler.AppCrashHandler$1 in onAppNotResponding at line 68
com.github.anrwatchdog.ANRWatchDog in run at line 212
```

So is there any way that I can get a workaround on it?

**Comment by bruno-garcia** [comment] 2019-07-02 14:34
ANRWatchDog is supposed to list the stack trace all running threads. Could you please list the others?
It doesn't seem like this thread was the main thread. In that case I believe we should see something like: `Caused by: com.github.anrwatchdog.ANRError$_$_Thread: main (state = WAITING)`.

From that stack trace it seems that the SDK captured an exception and by the time it was trying to send it out to Sentry, Android had already started shutting down the app.

**Comment by apue** [comment] 2019-07-04 07:40
@bruno-garcia Yes ANRWatchDog is supposed to list the stack traces of all the threads, however in this case, since it is a crash, the stack trace is captured by sentry, so only this thread's stack trace is dumped. and the strange things, since sentry will also capture and report during crash, I feel like there is no reason it only happens in ANRWatchDog (most of this kind crashes are from ANRWatchDog).

**Comment by bruno-garcia** [comment] 2019-07-06 07:35
@apue so that exact crash was actually captured by Sentry? It looks like the SDK was trying to schedule a thread to flush it and the process was already terminating.

**Comment by apue** [comment] 2019-07-09 04:01
@bruno-garcia I think so, I guess the sentry SDK is trying to upload the crash information, so it created some new thread (maybe by okhttp's dispatcher?)

**Comment by marandaneto** [comment] 2020-01-02 23:35
@apue hey, we've added support to ANR ootb (since v1.7.27), could you try the latest version (v1.7.29) and see if that works? please remove your own ANR integration, might be easier to test it and identify problems, thanks.

**Comment by apue** [comment] 2020-01-07 03:23
> @apue hey, we've added support to ANR ootb (since v1.7.27), could you try the latest version (v1.7.29) and see if that works? please remove your own ANR integration, might be easier to test it and identify problems, thanks.

Sure, will try it in the coming releases, thanks.

**Comment by marandaneto** [comment] 2020-01-31 13:15
@apue closing this issue, if you see that is still happening, let us know :)

**Closed by marandaneto** 2020-01-31 13:15 UTC
Labels: Android, question
