### ISSUE TITLE
Add configuration to easily exclude events based on exception

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#575] opened 2018-04-03 23:03 UTC
https://twitter.com/inodb/status/981292517898571776

```java
        Sentry.getStoredClient().addShouldSendEventCallback(new ShouldSendEventCallback() {
            public boolean shouldSend(Event event) {
                for (Map.Entry<String, SentryInterface> interfaceEntry : event.getSentryInterfaces().entrySet()) {
                    if (interfaceEntry.getValue() instanceof ExceptionInterface) {
                        ExceptionInterface i = (ExceptionInterface) interfaceEntry.getValue();
                        for (SentryException sentryException : i.getExceptions()) {
                            if (sentryException.getExceptionClassName().equals("foo") {
                                return false;
                            }
                        }
                    }
                }

                return true;
            }
        });
```

**Comment by miketeo** [comment] 2018-05-30 09:54
I will upvote on this: something similar like the [ignore_exceptions parameter](https://github.com/getsentry/raven-python/blob/master/docs/advanced.rst) in raven-python, and can be configured both in code or via sentry.properties will be great.

**Comment by afganhalbana** [comment] 2019-02-25 06:57
@bretthoerner @miketeo how do you guys solve this issue? i can't find any examples regarding this yet.

**Comment by Lucas-C** [comment] 2019-07-09 10:45
Thanks @bretthoerner for the code snippet !
We used it to make it configurable through an environment variable : https://github.com/voyages-sncf-technologies/hesperides/pull/691/files#diff-d729437ba7e0f7f1c29b2abda2d35318

**Comment by bruno-garcia** [comment] 2019-07-15 09:12
This could be built-in. So during `Sentry.init` one passes the types of Exceptions to ignore.

**Comment by maciejwalkowiak** [comment] 2020-10-01 10:49
This issue is a duplicate of https://github.com/getsentry/sentry-java/issues/761 but considering how frequently this feature is requested I am leaning towards adding this as a configuration option like @bruno-garcia suggested.

**Comment by buckett** [comment] 2021-03-04 07:40
I just came across this issue as I was trying to see if there was an easy way to filter out `org.springframework.security.web.firewall.RequestRejectedException` as when out services get scanned these generate lots of noise.

**Comment by maciejwalkowiak** [comment] 2021-03-04 12:47
@buckett right now it can be done through registering custom `BeforeSendCallback` where you can check the exception associated with an event and return null if event should be dropped.

**Comment by bruno-garcia** [comment] 2021-03-04 22:22
For reference, this is how it's done in .NET: https://docs.sentry.io/platforms/dotnet/ignoring-exceptions/

`SentrySdk.Init(o => o.AddExceptionFilterForType<OperationCanceledException>());`

In hindsight maybe not the best name `AddExceptionFilterForType`, perhaps `FilterException<TException>` would be a better candidate.

Today (v3.0.0 and above), it's similar to the original post (which is valid for SDK 1.7 and older):

```java
Sentry.init(options -> {
  options.setBeforeSend((event, _hint_) -> {
    return event.getThrowable() instanceof SQLException ? null : event;
  });
});
```

To avoid confusion I'll create a new issue and close this one.

**Closed by bruno-garcia** 2021-03-04 22:22 UTC
Labels: enhancement
