### ISSUE TITLE
An exception due to the connection occurred, a lockdown will be initiated

### ISSUE THREAD

**Issue by dario-frongillo** [getsentry/sentry-java#545] opened 2018-01-05 11:45 UTC
Hi All,
i use sentry-logback 
`        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry-logback</artifactId>
            <version>1.6.4</version>
        </dependency>`

I work behind http proxy so i have set on  sentry.properties  http.proxy.host and http.proxy.port.
All it works but there a lot of spam in my logback always with the same error that i will report in this message: 
`12:36:48.069 [sentry-pool-1-thread-1] WARN  i.s.connection.AbstractConnection - [AbstractConnection.java:93] An exception due to the connection occurred, a lockdown will be initiated. 
io.sentry.connection.ConnectionException: {}
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:192) ~[sentry-1.6.4.jar:na]
	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71) ~[sentry-1.6.4.jar:na]
	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171) [sentry-1.6.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://sentry.io/api/267193/store/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_144]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_144]
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:157) ~[sentry-1.6.4.jar:na]
	... 5 common frames omitted
12:36:48.069 [sentry-pool-1-thread-1] ERROR i.sentry.connection.AsyncConnection - [AsyncConnection.java:175] An exception occurred while sending the event to Sentry. 
io.sentry.connection.ConnectionException: {}
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:192) ~[sentry-1.6.4.jar:na]
	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:71) ~[sentry-1.6.4.jar:na]
	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171) ~[sentry-1.6.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://sentry.io/api/267193/store/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_144]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_144]
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:157) ~[sentry-1.6.4.jar:na]
	... 5 common frames omitted

**Comment by bretthoerner** [comment] 2018-01-08 15:53
HTTP 429 is being returned because you are being rate limited (sending too many events for your Sentry plan).

Does it continuously spam or does it stop for a while? We implemented backoff for this so it shouldn't be spamming nonstop.

**Comment by adrian-baker** [comment] 2018-02-21 21:08
Possibly same as https://github.com/getsentry/sentry-java/issues/559 .

**Comment by bruno-garcia** [comment] 2019-07-15 11:41
Duplicate of #559

**Closed by bruno-garcia** 2019-07-15 11:41 UTC
