### ISSUE TITLE
Java Source Context

### ISSUE THREAD

**Issue by fprochazka** [getsentry/sentry-java#633] opened 2018-11-06 11:12 UTC
Edit by maintainers: We've put Java Source Context on our roadmap. More details and progress can be found in a comment further down (https://github.com/getsentry/sentry-java/issues/633#issuecomment-1465599120)

## Summary

I would like to be able to see sources in stacktraces of java exceptions, the same way they're visible for javascript.

## Motivation

This would improve my ability to see the problem in the context of my application.

## Additional Context

Sentry java client, should be able to access `classpath` of the running application and build process should be able to provide versions of installed libraries and built artefacts. Combining these two informations, Sentry should be able to render source code of Java. This would allow you to render on at least *some* frames of the stacktrace (there will always be generated/proxy frames, that will have no "visible" source code available).

By uploading correct artifact (with sources) to a release, I should be able fill in the main part - source code of my own application.

And it would be ideal, if fetching "public" maven jars with sources could be a native part of Sentry, since these libraries take up a massive amount of disk storage, and if they would duplicate on each release, this would be unfeasible. Having a shared cache between releases would be ideal.

## Refs

* https://github.com/getsentry/sentry/issues/10435

**Comment by yurik94** [comment] 2019-09-03 10:57
Still not possible?

**Comment by arvkonstantin** [comment] 2021-06-30 09:24
Still not possible?

**Comment by romtsn** [comment] 2022-02-16 15:42
Still not possible?

**Comment by mitsuhiko** [comment] 2022-05-31 10:10
So I tried doing this a few years ago and mainly ran into complications with the tooling and introspection. For source context to work we would like to ideally piggyback on the [source bundle system](https://getsentry.github.io/symbolicator/advanced/source-bundles/) we use for a few other platforms. For this to work we need to do the following things:

* send up the ID of the source bundle with the event is sent
* get the file name of the file that declares a java class
* look up the source by file name in the source bundle

There are a handful of restrictions unfortunately. The biggest one is that the file name does not actually exist in the stack trace. This is not an unsolvable problem as we could derive made up file names based on the class path (replace `.` with `/` and add `.java` to the end). However I was unable to actually create the source bundle in a good way as there (at the time) did not appear to be a standardized way to hook into the .jar creation process to extract the source files.

There were also too many different build systems (gradle, maven etc.) to make this work _and_ a lot of code uses published maven archives and it was unclear how we get access to those sources.

So maybe a new approach could be found where we leverage the gradle plugin for Android as a first step and start creating source bundles there. For the build ID to give the bundle we could use a similar system as we already use for the proguard files. Then we have a starting point and can see if there is a way to expand it from there.

**Comment by maciejwalkowiak** [comment] 2022-06-01 06:12
> Most artifacts can be found on public maven registry, but some will be privately published on company's internal package registry, which would make fetching the sourcecode a bit harder.

I think it's fair to assume that if a company uses internal package registry, to get source context support they must publish there sources jars as well.

**Comment by adinauer** [comment] 2023-03-13 06:50
We had a call and discusses steps to build this in a bit more detail. We'll update this list as we learn and keep finding out more info.

## ❓ Unclear / input appreciated 🙏 :
- How does Java debug with attached sources work? How does it find the right source when you (remote) debug code in IDE?

## Steps
### During build time
- [ ] In build system (gradle, SAGP for starters) we have to hook into the build and gain access to the sources
- [ ] Generate ID for source bundle
- [ ] Pass sources and ID to sentry-cli from build system
	- Input could be a path 
	- Later on we might also support sources.jar files
- [ ] In sentry-cli
	- [ ] Turn source into a bundle
	- [ ] more TBD ...
- [ ] Embed bundle ID into app / JAR / ... so it can be read at runtime

### During runtime
- [ ] Read all available bundle IDs
- [ ] Send bundle IDs with events

### For matching running code to source
- [ ] Use filename and package substring from module/classname by looking at stack frame
	- [ ] Filename and class name don't have to match (e.g. multiple classes in a file in kotlin)
	- [ ] use `${package}.${filename}` as lookup (may need to replace `.` with `/`)

### Other TODOs
- [ ] Might need to update manifest structure of source bundles to support dotted notation instead of paths
- [ ] Probably won't need symbolicator but there's no way to just look up source code yet, may need to change that

## Known limitations
- for kotlin it will probably be a known limitation that packages and folder structure have to match (i.e. can't put code in root dir or wrong dir and only rely on package declaration in file)

## Things to test
- [ ] Android
- [ ] Bytecode manipulation on Android
- [ ] Java Agent manipulation on backend
- [ ] Generated code
- [ ] Kotlin code

**Comment by adinauer** [comment] 2023-05-17 10:48
We've just released Source Context support for Android. Please give it a try: https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/3.7.0 (which uses https://github.com/getsentry/sentry-java/releases/tag/6.19.0)

Any feedback is welcome 🙏 

We're still working on adding Source Context for Backend etc. - stay tuned.

**Comment by beheh** [comment] 2023-05-26 11:18
I'm not quite sure where to ask this, but I thought here was more appropriate than the sentry-android-gradle-plugin PR and because you specifically asked for feedback:

Is there a path to source code uploading for Android with `isMinifyEnabled` set to false? For example, in a small app with have disabled minification for better stack traces and reproducibility. However it seems right now minification is a requirement for uploading (as per getsentry/sentry-android-gradle-plugin#86).

**Comment by romtsn** [comment] 2023-05-26 11:54
> I'm not quite sure where to ask this, but I thought here was more appropriate than the sentry-android-gradle-plugin PR and because you specifically asked for feedback:
> 
> Is there a path to source code uploading for Android with `isMinifyEnabled` set to false? For example, in a small app with have disabled minification for better stack traces and reproducibility. However it seems right now minification is a requirement for uploading (as per [getsentry/sentry-android-gradle-plugin#86](https://github.com/getsentry/sentry-android-gradle-plugin/pull/86)).
> 
> Or maybe this is more of a hosted Sentry question, where we're used to have source code available for non-processed files in e.g. Python and/or direct links to GitHub. It would be nice if we were able to have a similar experience in the issue interface to see source code directly in Sentry for context.

The PR linked is rather about uploading proguard mappings, but not the source context. For source context we just hook into  the `release` build type. So if you're running `assembleRelease` and have the `includeSourceContext` flag enabled, you should be good.

As for self-hosted - yes you'd have to update to the latest version, as there were some necessary changes on the stacktrace processing.

**Comment by beheh** [comment] 2023-05-26 11:59
I see now, I spoke to soon. With `includeSourceContext` explicitly set it all works! The line above ("If you aren't using ProGuard (yet), you'll have to supply some properties.") confused me because it made it sound like ProGuard is a requirement. Thanks!

**Comment by adinauer** [comment] 2023-05-30 05:11
I've added another sentence to clarify ProGuard isn't a requirement for using Source Context.

**Comment by adinauer** [comment] 2023-06-01 06:55
We have now released Java Source Context support for Backend, Desktop, etc. via Gradle and Maven as well. Please take a look at https://github.com/getsentry/sentry-java/issues/633#issuecomment-1465599120 for more details.

Docs are coming soon.

**Comment by adinauer** [comment] 2023-06-09 09:35
Docs shave now been merged and can be found here:
- [Android](https://docs.sentry.io/platforms/android/source-context/)
- [Java](https://docs.sentry.io/platforms/java/source-context/)

Closing this now. We can do improvements in separate issues.

**Closed** 2023-06-09 09:37 UTC
Labels: enhancement, Platform: Java, Effort: Large, Impact: Large

**Comment by adinauer** [comment] 2023-07-20 06:55
@androidacy-user thanks for bringing this up, we'll improve docs. I've created https://github.com/getsentry/sentry-java/issues/2854 to track.
