### ISSUE TITLE
Flaky test `SentryTracerTest - idle transaction with children`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#2169] opened 2022-07-12 17:17 UTC
### Description

https://github.com/getsentry/sentry-java/runs/7306389891?check_suite_focus=true

```
io.sentry.SentryTracerTest > when idle transaction with children, finishes the transaction after the idle timeout FAILED
    Wanted but not invoked:
    hub.captureTransaction(
        <any>,
        <any>,
        <any>,
        <any>
    );
    -> at io.sentry.Hub.captureTransaction(Hub.java:606)
    However, there were exactly 6 interactions with this mock:
    hub.bindClient(
        Mock for ISentryClient, hashCode: 762599953
    );
    -> at io.sentry.SentryTracerTest$Fixture.<init>(SentryTracerTest.kt:33)
    hub.isEnabled();
    -> at io.sentry.Hub.bindClient(Hub.java:559)
    hub.getOptions();
    -> at io.sentry.SentryTracer.finish(SentryTracer.java:298)
    hub.configureScope(
        io.sentry.SentryTracer$$Lambda$204/0x000000080044d440@283d9ddd
    );
    -> at io.sentry.SentryTracer.finish(SentryTracer.java:331)
    hub.isEnabled();
    -> at io.sentry.Hub.configureScope(Hub.java:542)
    hub.getOptions();
    -> at io.sentry.SentryTracer.createChild(SentryTracer.java:264)
        at app//io.sentry.Hub.captureTransaction(Hub.java:606)
        at app//io.sentry.SentryTracerTest.when idle transaction with children, finishes the transaction after the idle timeout(SentryTracerTest.kt:704)
```

**Comment by romtsn** [comment] 2022-07-12 17:25
dupe of #2143

**Closed by romtsn** 2022-07-12 17:25 UTC
Labels: Platform: Java
