### ISSUE TITLE
Unable to set tags at different levels

### ISSUE THREAD

**Issue by mmadoo** [getsentry/sentry-java#874] opened 2020-07-24 13:14 UTC
If sentry is configured  for instance in sentry.properties with tags=commitHash:a5e39b08 and has env property, SENTRY_TAGS="namespaceK8s:test", then tags map is `{ namespaceK8s: test } `while I would have expect tags to be merged in `{ namespaceK8s: test,  commitHash: a5e39b08}`.

I could prepare a pull request to fix it, but I would to know if it may be accepted before.

**Comment by marandaneto** [comment] 2020-07-26 11:17
@mmadoo thanks for raising this, looks like a bug.
@bruno-garcia is it indeed a bug or intended to be like this? ideas?

**Comment by bruno-garcia** [comment] 2020-07-26 13:58
Looks like it was an oversight indeed. A PR would be most welcomed. Thanks.

**Comment by marandaneto** [comment] 2020-09-29 08:11
@bruno-garcia @maciejwalkowiak do you know if we merge configurations or one is a precedence of the other?

**Comment by maciejwalkowiak** [comment] 2020-09-29 08:44
In v3 we do not merge configurations and we do not support setting tags externally. Perhaps something for 3.1?

**Comment by marandaneto** [comment] 2020-09-29 08:49
sounds good

**Comment by mmadoo** [comment] 2020-09-29 09:05
With #875, merge is done for tags (see https://github.com/DCbrainOrg/sentry-java/blob/0d6c3d45c66e68fbbe265c988e84825421f8c872/sentry/src/test/java/io/sentry/DefaultSentryClientFactoryTest.java#L69 )

**Comment by marandaneto** [comment] 2020-09-29 09:35
> With #875, merge is done for tags (see https://github.com/DCbrainOrg/sentry-java/blob/0d6c3d45c66e68fbbe265c988e84825421f8c872/sentry/src/test/java/io/sentry/DefaultSentryClientFactoryTest.java#L69 )

yep for v1.x, my comment was about the new version v3.x

**Comment by maciejwalkowiak** [comment] 2020-10-01 08:08
In case of v3 we would need to add `tags` property to `SentryOptions` and likely set them on events in `MainEventProcessor` or some other event processor. If it's something you @marandaneto  agree with I can take care of preparing the PR.

**Comment by bruno-garcia** [comment] 2020-10-01 20:46
I don't think we have this in the unified API.
In ASP.NET Core I've added that as `options.DefaultTags` which bind to the framework's config system

So if you set things in the appseettinggs.json file, it ends up on all events (the integration basically does `configureScope(s -> s.setTag(defaultTags)` on startup

**Comment by marandaneto** [comment] 2020-10-16 08:22
@bruno-garcia  wondering if we should close it as non-supported or a feature request? as it's not a bug on v3, but actually a feature request which is not part of our unified API.

**Comment by bruno-garcia** [comment] 2020-10-16 16:32
Agree it isn't a bug, it's a feature we dropped. Lets keep it open while we discuss how to proceed here.
We're considering adding an _integration_ that will bind `SENTRY_` things into sentry options. Lets see how relevant to folks this is to prioritize this.

We either work on performance support or 1000 ways to load configs into the SDK. I believe we'd add more value adding performance support

**Comment by marandaneto** [comment] 2020-10-17 09:23
I agree, maybe the community could help with it, we accept PRs :)

**Comment by maciejwalkowiak** [comment] 2021-08-17 13:36
Tags can. be set now using environment variables and system properties: https://docs.sentry.io/platforms/java/configuration/#tags

I believe this issue can be closed.

**Comment by marandaneto** [comment] 2021-08-17 14:40
@maciejwalkowiak I believe the issue here is about merging tags and not really setting in different ways, do we merge tags already?

**Comment by maciejwalkowiak** [comment] 2021-08-18 12:25
@marandaneto got it. #1656 addresses merging tags.

**Closed** 2021-08-18 14:31 UTC
Labels: enhancement, help wanted, Legacy SDK
