### ISSUE TITLE
Manual Proguard Support to deobfuscate Sentry Stacktrace.

### ISSUE THREAD

**Issue by shahbaz-payu** [getsentry/sentry-java#1519] opened 2021-06-07 12:55 UTC
_Platform:_
- [ ]  Android 

_IDE:_
- [ ]  Android Studio -> If yes, which version? 4.1.2

_Build system:_
- [ ]  Gradle -> If yes, which version? 4.1.3
_Android Gradle Plugin:_

_Sentry Android Gradle Plugin:_
- [ ] Sentry Url: https://sentry.payu.in/api/32/store/

_Proguard/R8:_
- [ ]  Enabled

The version of the SDK:
Using API  based solution
API Url: https://sentry.payu.in/api/32/store/

---
I have the following issue:

We are using APIs based solution of Sentry.
Firstly, we send crash logs to Sentry from our multiple libraries/SDKs. We need to upload mapping.txt for every with its corresponding versions.

Secondly, we also upload a mapping.txt file of an SDK on which the crash occurs. But it still shows obfuscated filename.
https://sentry.payu.in/payu/mobile-data/issues/193322 You can check it here.
event_id: "87ca98f138d446d8a9040277823bce5b"

**Steps to reproduce:**
- Step

**Actual result:**
- We could get deobfuscate the filename and symbols while uploading mapping file for the library.

**Expected result:**
We are looking for a solution to upload mapping.txt file from the Sentry dashboard corresponding to the release tag/version.

Please suggest us a solution.

**Comment by marandaneto** [comment] 2021-06-07 14:17
Hi, to get deobfuscated stack traces, you have to integrate the Sentry Gradle plugin https://docs.sentry.io/platforms/android/proguard/
this would work for the final App's and not libraries/SDKs since the mapping file would change when the final App compiles, See this issue https://github.com/getsentry/sentry-android-gradle-plugin/issues/3
also, it'd also require https://github.com/getsentry/sentry-java/issues/1236 if you still wanna do it manually.

Closing it since it's not a bug but a feature request that is being tracked in the linked issues.

**Closed by marandaneto** 2021-06-07 14:17 UTC

**Comment by shahbaz-payu** [comment] 2021-06-09 07:12
@marandaneto 
Thanks, but we have some different scenario.
I already uploaded the proguard mapping.txt file to the **Sentry dashboard through sentry-cli.**
Also added mapping file uuid to the Sentry request, "debug_meta":{"images":[{"type":"proguard","uuid":"a33e3627-f443-5879-ad16-280734d221ea"}]} **Attached the complete JSON of the event.**
[sentry_json_mapping.txt](https://github.com/getsentry/sentry-java/files/6621740/sentry_json_mapping.txt)

**Sentry Backend/Dashboard Version: Sentry 9.1.0**
Could you please check it?

**Comment by marandaneto** [comment] 2021-06-09 07:22
@shahbaz-payu as its written in the linked issues, when using in libraries, the mapping file is overwritten when compiled by the final App, nothing we can do, tell your customers to report the issues for you, they should upload the mapping file to their sentry server or sentry.io.
you use sentry onpremise, I can't log in and check things.
maybe update your sentry instance to use the latest version https://github.com/getsentry/sentry/releases
there were improvements for demangling java stack traces in the past.
