### ISSUE TITLE
Sentry Java 3.0 drops OSGi support

### ISSUE THREAD

**Issue by talios** [getsentry/sentry-java#983] opened 2020-10-15 05:11 UTC
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> Version 3
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [X] Maven Central
- [ ] Manually

The version of the SDK:
**3.0.0**

---
After upgrading from the old 1.7.x version to 3.x.x I discover that OSGi support has been dropped along the way, but there seems no tickets/issues raised around this.

```
jshell> new java.util.jar.JarFile("/Users/amrk/.m2/repository/io/sentry/sentry/1.7.30/sentry-1.7.30.jar").getManifest().getMainAttributes().keySet()
$3 ==> [Manifest-Version, Bundle-Description, Automatic-Module-Name, Bundle-SymbolicName, Built-By, Bnd-LastModified, Bundle-ManifestVersion, Import-Package, Require-Capability, Tool, Export-Package, Bundle-Name, Bundle-Version, Private-Package, Created-By, Build-Jdk]
jshell> new java.util.jar.JarFile("/Users/amrk/.m2/repository/io/sentry/sentry/3.0.0/sentry-3.0.0.jar").getManifest().getMainAttributes().keySet()
$4 ==> [Manifest-Version]
```

**Comment by talios** [comment] 2020-11-03 20:46
No updates/comments on this? We've worked around it by embedded and re-exporting sentry from the bundle we're configuring/setting up sentry, but would good to see the upstream support return.

**Comment by mh03r932** [comment] 2020-11-06 17:32
There seems to be a rather old issue already open for this.
https://github.com/getsentry/sentry-java/issues/358

**Comment by marandaneto** [comment] 2020-12-11 10:19
@maciejwalkowiak do you know if we intend to support OSGi or why have we dropped it? at least docs about it would be cool.

**Comment by maciejwalkowiak** [comment] 2020-12-29 16:14
@marandaneto we do and will add back OSGi support, just it doesn't have high priority. Ideally, it's contributed by the community.

**Comment by adinauer** [comment] 2022-04-06 12:35
Duplicate of https://github.com/getsentry/sentry-java/issues/358

**Closed by adinauer** 2022-04-06 12:35 UTC
Labels: documentation, up-for-grabs, Platform: Java, OSGi
