### ISSUE TITLE
DSN is required. Use empty string to disable SDK when building Native in Spring Boot

### ISSUE THREAD

**Issue by JakobStadlhuber** [getsentry/sentry-java#2742] opened 2023-05-29 12:43 UTC
### Integration

sentry

### Java Version

17

### Spring Boot Version

3.0.7
and plugin with id("org.graalvm.buildtools.native") version "0.9.20"

I tried it on an M1 with this additional option:
`kotlin
tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootBuildImage> {
    if (org.gradle.nativeplatform.platform.internal.DefaultNativePlatform.getCurrentArchitecture().isArm) {
        builder.set("dashaun/builder-arm:tiny")
    }
}
`

### Version

6.20.0 (logback, sentry-jdbc, sentry-spring-boot-starter-jakarta)

### Steps to Reproduce

1. Configure Sentry with application.properties (sentry.dsn=xxxx)
2. `gradle bootBuildImage`

### Expected Result

No error when building the native image

### Actual Result

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sentryTransactionAdvice' defined in class path resource [io/sentry/spring/jakarta/tracing/SentryAdviceConfiguration.class]: Unsatisfied dependency expressed through method 'sentryTransactionAdvice' parameter 0: Error creating bean with name 'sentryHub' defined in class path resource [io/sentry/spring/boot/jakarta/SentryAutoConfiguration$HubConfiguration.class]: Failed to instantiate [io.sentry.IHub]: Factory method 'sentryHub' threw exception with message: DSN is required. Use empty string to disable SDK.

**Comment by JakobStadlhuber** [comment] 2023-05-29 12:44
I tried it on an M1 with this additional option:

`tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootBuildImage> {
    if (org.gradle.nativeplatform.platform.internal.DefaultNativePlatform.getCurrentArchitecture().isArm) {
        builder.set("dashaun/builder-arm:tiny")
    }
}`

**Comment by bj97301** [comment] 2023-05-29 22:42
Happening to me too.  Going to have to disable sentry to fix prod build till I get this figured out =/

**Comment by bj97301** [comment] 2023-05-29 23:25
i got this error when i set debug to a string value instead of a bool recently

**Comment by adinauer** [comment] 2023-05-30 07:19
@JakobStadlhuber please let us know if @bj97301's comment helped to fix your problem.

**Comment by bj97301** [comment] 2023-05-30 08:38
> @JakobStadlhuber please let us know if @bj97301's comment helped to fix your problem.

Can we get a better error message for this though?

**Comment by adinauer** [comment] 2023-05-30 09:38
@bj97301 we'll look into improving the error message.

**Comment by JakobStadlhuber** [comment] 2023-06-08 12:31
> @JakobStadlhuber please let us know if @bj97301's comment helped to fix your problem.

No, 

I use no debugging and the problem still appears:
`sentry.dsn=
# Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
# We recommend adjusting this value in production.
sentry.traces-sample-rate=1.0
sentry.environment=dev`

I tried it with `sentry.debug=false` still the same error.

**Comment by adinauer** [comment] 2023-06-09 07:58
@JakobStadlhuber can you please try without `sentry.traces-sample-rate=1.0` in your `application.properties`?

**Comment by adinauer** [comment] 2023-06-12 12:15
Could you please also give the following a try:

```
  @Bean
  Sentry.OptionsConfiguration<SentryOptions> optionsConfiguration() {
    return new Sentry.OptionsConfiguration<SentryOptions>() {
      @Override
      public void configure(@NotNull SentryOptions options) {
        options.setTracesSampleRate(1.0);
      }
    };
  }
```

**Comment by adinauer** [comment] 2023-06-14 13:10
This could be related to AOP. When I tried some possible fixes while on the branch for https://github.com/getsentry/sentry-java/pull/2764 I wasn't able to fix it. Need to check if disabling all AOP related things gets rid of the problem.

**Comment by JakobStadlhuber** [comment] 2023-07-22 19:07
Are there any news on this?

**Comment by adinauer** [comment] 2023-07-24 05:12
Hello @JakobStadlhuber not yet. Working on something else at the moment. Can't say yet when I'll get to this - sorry.

**Comment by lbloder** [comment] 2023-09-06 08:45
Hi @JakobStadlhuber,
Sorry for the delay. With #2915 we're introducing a new property: `sentry.enable-aot-compatibility` that you can set to true in the `application.properties`. This disables the AOP related functionality (e.g. `@SentryTransaction` and `@SentrySpan`) which interfered with building for graalvm. As soon as this is merged and included in a Release you can give it a try.

In order to then successfully run it, it is still required to create the .json hint files for reflection, proxies etc. There's a java agent that automatically creates these for you. Documentation on that can be found here: https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.using-the-tracing-agent.

Looking forward to your feedback.

**Comment by adinauer** [comment] 2023-09-18 12:15
Let's keep this open until we have some feedback.

**Comment by adinauer** [comment] 2023-10-02 12:05
@JakobStadlhuber can you please retest with `sentry.enable-aot-compatibility=true`?

**Closed** 2023-10-02 12:25 UTC
Labels: Type: Bug, Platform: Java

**Comment by melyux** [comment] 2024-09-06 08:08
@julien-lisub Bless you. This worked after days of trying to debug. Terrible error message from Sentry. Why are .env* booleans strings in Android but real booleans in iOS, using the same exact Expo code?

**Comment by akhil-handa** [comment] 2024-10-29 10:25
`2024-10-29 15:50:40: Launching testRoomMigrations23Onwards() on 'NEWPOS NEW9220.
Running tests
Executing tasks: [:libtmtu:connectedDebugAndroidTest] in project /Users/akhilhanda/Documents/projects/etim_app/ETIM


> Configure project :
Build file '/Users/akhilhanda/Documents/projects/etim_app/ETIM/build.gradle': line 102
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 9.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.6/userguide/upgrading_version_6.html#jcenter_deprecation
	at build_ec0sdstkbffwvt4kr6omzxkbf$_run_closure2$_closure6.doCall$original(/Users/akhilhanda/Documents/projects/etim_app/ETIM/build.gradle:102)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)
	at build_ec0sdstkbffwvt4kr6omzxkbf$_run_closure2.doCall$original(/Users/akhilhanda/Documents/projects/etim_app/ETIM/build.gradle:101)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :app
AGPBI: {"kind":"warning","text":"The option setting 'android.experimental.testOptions.emulatorSnapshots.maxSnapshotsForTestFailures=0' is experimental.","sources":[{}]}
AGPBI: {"kind":"warning","text":"Using flatDir should be avoided because it doesn't support any meta-data formats.","sources":[{}]}
Ignore Variant: stagingRelease
Ignore Variant: preprodRelease
Ignore Variant: digitalReleaseBuild
Ignore Variant: productionReleaseBuild
Ignore Variant: prodBestReleaseBuild
Ignore Variant: telpoReleaseBuild
Task -> testDigitalDebugUnitTest
Task -> testDigitalReleaseUnitTest
Task -> testDigitalReleaseBuildUnitTest
Task -> testPreprodDebugUnitTest
Task -> testPreprodReleaseUnitTest
Task -> testPreprodReleaseBuildUnitTest
Task -> testProdBestDebugUnitTest
Task -> testProdBestReleaseUnitTest
Task -> testProdBestReleaseBuildUnitTest
Task -> testProductionDebugUnitTest
Task -> testProductionReleaseUnitTest
Task -> testProductionReleaseBuildUnitTest
Task -> testStagingDebugUnitTest
Task -> testStagingReleaseUnitTest
Task -> testStagingReleaseBuildUnitTest
Task -> testTelpoDebugUnitTest
Task -> testTelpoReleaseUnitTest
Task -> testTelpoReleaseBuildUnitTest

> Configure project :chaloCard
AGPBI: {"kind":"warning","text":"Using flatDir should be avoided because it doesn't support any meta-data formats.","sources":[{}]}

> Configure project :libtmtu
Task -> testDebugUnitTest
Task -> testReleaseUnitTest

> Configure project :wirelessEtimCommFeature
AGPBI: {"kind":"warning","text":"Using flatDir should be avoided because it doesn't support any meta-data formats.","sources":[{}]}

> Task :libservices:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :libtmtu:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :chaloMonitor:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :libtmtu:preBuild UP-TO-DATE
> Task :libtmtu:preDebugBuild UP-TO-DATE
> Task :utilities:preBuild UP-TO-DATE
> Task :libservices:preBuild UP-TO-DATE
> Task :utilities:preDebugBuild UP-TO-DATE
> Task :libtmtu:generateDebugResValues UP-TO-DATE
> Task :libservices:preDebugBuild UP-TO-DATE
> Task :libservices:generateDebugResValues UP-TO-DATE
> Task :chaloMonitor:preBuild UP-TO-DATE
> Task :chaloMonitor:preDebugBuild UP-TO-DATE
> Task :chaloMonitor:generateDebugBuildConfig UP-TO-DATE
> Task :chaloMonitor:generateDebugResValues UP-TO-DATE
> Task :libtmtu:generateDebugResources UP-TO-DATE
> Task :chaloMonitor:generateDebugResources UP-TO-DATE
> Task :libservices:generateDebugResources UP-TO-DATE
> Task :chaloMonitor:packageDebugResources UP-TO-DATE
> Task :utilities:compileDebugAidl NO-SOURCE
> Task :utilities:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :utilities:generateDebugResValues UP-TO-DATE
> Task :libtmtu:packageDebugResources UP-TO-DATE
> Task :chaloMonitor:parseDebugLocalResources UP-TO-DATE
> Task :libservices:packageDebugResources UP-TO-DATE
> Task :chaloMonitor:generateDebugRFile UP-TO-DATE
> Task :libtmtu:parseDebugLocalResources UP-TO-DATE
> Task :libservices:parseDebugLocalResources UP-TO-DATE
> Task :utilities:javaPreCompileDebug UP-TO-DATE
> Task :libtmtu:generateDebugRFile UP-TO-DATE
> Task :utilities:writeDebugAarMetadata UP-TO-DATE
> Task :libservices:generateDebugRFile UP-TO-DATE
> Task :utilities:processDebugManifest UP-TO-DATE
> Task :utilities:mergeDebugShaders UP-TO-DATE
> Task :utilities:compileDebugShaders NO-SOURCE
> Task :utilities:generateDebugAssets UP-TO-DATE
> Task :utilities:packageDebugAssets UP-TO-DATE
> Task :utilities:mergeDebugJniLibFolders UP-TO-DATE
> Task :utilities:mergeDebugNativeLibs NO-SOURCE
> Task :utilities:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :libservices:javaPreCompileDebug UP-TO-DATE
> Task :libtmtu:javaPreCompileDebug UP-TO-DATE
> Task :libtmtu:preDebugAndroidTestBuild UP-TO-DATE
> Task :libtmtu:writeDebugAarMetadata UP-TO-DATE
> Task :libservices:compileDebugLibraryResources UP-TO-DATE
> Task :libservices:writeDebugAarMetadata UP-TO-DATE
> Task :libtmtu:compileDebugLibraryResources UP-TO-DATE
> Task :libservices:extractDeepLinksDebug UP-TO-DATE
> Task :libtmtu:generateDebugAndroidTestResValues UP-TO-DATE
> Task :libservices:processDebugManifest UP-TO-DATE
> Task :libtmtu:generateDebugAndroidTestResources UP-TO-DATE
> Task :libservices:mergeDebugShaders UP-TO-DATE
> Task :libservices:compileDebugShaders NO-SOURCE
> Task :libservices:generateDebugAssets UP-TO-DATE
> Task :libtmtu:extractDeepLinksDebug UP-TO-DATE
> Task :libservices:packageDebugAssets UP-TO-DATE
> Task :libtmtu:processDebugManifest UP-TO-DATE
> Task :libtmtu:javaPreCompileDebugAndroidTest UP-TO-DATE
> Task :libtmtu:mergeDebugAndroidTestShaders UP-TO-DATE
> Task :libtmtu:compileDebugAndroidTestShaders NO-SOURCE
> Task :libtmtu:generateDebugAndroidTestAssets UP-TO-DATE
> Task :libtmtu:mergeDebugShaders UP-TO-DATE
> Task :libtmtu:compileDebugShaders NO-SOURCE
> Task :libtmtu:generateDebugAssets UP-TO-DATE
> Task :libtmtu:packageDebugAssets UP-TO-DATE
> Task :libservices:configureCMakeDebug[armeabi-v7a]
> Task :libservices:buildCMakeDebug[armeabi-v7a]
> Task :libservices:mergeDebugJniLibFolders UP-TO-DATE
> Task :libservices:mergeDebugNativeLibs UP-TO-DATE
> Task :libservices:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :libtmtu:desugarDebugAndroidTestFileDependencies UP-TO-DATE
> Task :chaloMonitor:compileDebugKotlin UP-TO-DATE
> Task :chaloMonitor:javaPreCompileDebug UP-TO-DATE
> Task :chaloMonitor:compileDebugJavaWithJavac UP-TO-DATE
> Task :chaloMonitor:bundleLibCompileToJarDebug UP-TO-DATE
> Task :chaloMonitor:packageDebugRenderscript NO-SOURCE
> Task :chaloMonitor:compileDebugLibraryResources UP-TO-DATE
> Task :chaloMonitor:writeDebugAarMetadata UP-TO-DATE
> Task :chaloMonitor:extractDeepLinksDebug UP-TO-DATE
> Task :libtmtu:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
> Task :chaloMonitor:mergeDebugShaders UP-TO-DATE
> Task :chaloMonitor:compileDebugShaders NO-SOURCE
> Task :chaloMonitor:generateDebugAssets UP-TO-DATE
> Task :chaloMonitor:packageDebugAssets UP-TO-DATE
> Task :chaloMonitor:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :chaloMonitor:processDebugJavaRes UP-TO-DATE
> Task :chaloMonitor:bundleLibRuntimeToDirDebug UP-TO-DATE
> Task :libtmtu:checkDebugAndroidTestAarMetadata UP-TO-DATE

> Task :chaloMonitor:processDebugManifest
package="com.chalo.chalomonitor" found in source AndroidManifest.xml: /Users/akhilhanda/Documents/projects/etim_app/ETIM/chaloMonitor/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.chalo.chalomonitor" from the source AndroidManifest.xml: /Users/akhilhanda/Documents/projects/etim_app/ETIM/chaloMonitor/src/main/AndroidManifest.xml.

> Task :chaloMonitor:mergeDebugJniLibFolders UP-TO-DATE
> Task :chaloMonitor:mergeDebugNativeLibs NO-SOURCE
> Task :chaloMonitor:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :libtmtu:mergeDebugAndroidTestAssets UP-TO-DATE
> Task :libtmtu:compressDebugAndroidTestAssets UP-TO-DATE
> Task :libtmtu:mergeExtDexDebugAndroidTest UP-TO-DATE
> Task :libtmtu:mergeDebugJniLibFolders UP-TO-DATE
> Task :libtmtu:mergeDebugNativeLibs NO-SOURCE
> Task :libtmtu:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :libtmtu:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
> Task :utilities:compileDebugRenderscript UP-TO-DATE
> Task :utilities:generateDebugResources UP-TO-DATE
> Task :utilities:packageDebugResources UP-TO-DATE
> Task :libtmtu:mergeDebugAndroidTestNativeLibs UP-TO-DATE
> Task :utilities:parseDebugLocalResources UP-TO-DATE
> Task :utilities:generateDebugRFile UP-TO-DATE
> Task :libtmtu:mapDebugAndroidTestSourceSetPaths UP-TO-DATE
> Task :libtmtu:mergeDebugAndroidTestResources UP-TO-DATE
> Task :libtmtu:stripDebugAndroidTestDebugSymbols UP-TO-DATE
> Task :libtmtu:validateSigningDebugAndroidTest UP-TO-DATE
> Task :libtmtu:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
> Task :utilities:compileDebugKotlin UP-TO-DATE
> Task :utilities:compileDebugJavaWithJavac UP-TO-DATE
> Task :utilities:bundleLibCompileToJarDebug UP-TO-DATE
> Task :utilities:extractDeepLinksDebug UP-TO-DATE
> Task :utilities:compileDebugLibraryResources UP-TO-DATE
> Task :utilities:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :utilities:processDebugJavaRes UP-TO-DATE
> Task :utilities:bundleLibRuntimeToDirDebug UP-TO-DATE
> Task :libservices:kspDebugKotlin UP-TO-DATE
> Task :libtmtu:processDebugAndroidTestManifest
> Task :libservices:kaptGenerateStubsDebugKotlin UP-TO-DATE
> Task :libservices:kaptDebugKotlin UP-TO-DATE
> Task :libservices:compileDebugKotlin UP-TO-DATE
> Task :libservices:compileDebugJavaWithJavac UP-TO-DATE
> Task :libservices:bundleLibCompileToJarDebug UP-TO-DATE
> Task :libservices:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :libservices:processDebugJavaRes UP-TO-DATE
> Task :libservices:bundleLibRuntimeToDirDebug UP-TO-DATE
> Task :libtmtu:kspDebugKotlin UP-TO-DATE
> Task :libtmtu:kaptGenerateStubsDebugKotlin UP-TO-DATE
> Task :libtmtu:kaptDebugKotlin UP-TO-DATE
> Task :libtmtu:compileDebugKotlin UP-TO-DATE
> Task :libtmtu:compileDebugJavaWithJavac UP-TO-DATE
> Task :libtmtu:bundleLibCompileToJarDebug UP-TO-DATE
> Task :libtmtu:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :libtmtu:processDebugJavaRes UP-TO-DATE
> Task :libtmtu:bundleLibRuntimeToDirDebug UP-TO-DATE
> Task :libtmtu:mergeLibDexDebugAndroidTest UP-TO-DATE
> Task :libtmtu:processDebugAndroidTestResources
> Task :libtmtu:kspDebugAndroidTestKotlin UP-TO-DATE
> Task :libtmtu:kaptGenerateStubsDebugAndroidTestKotlin UP-TO-DATE
> Task :libtmtu:kaptDebugAndroidTestKotlin UP-TO-DATE
> Task :libtmtu:compileDebugAndroidTestKotlin UP-TO-DATE
> Task :libtmtu:compileDebugAndroidTestJavaWithJavac NO-SOURCE
> Task :libtmtu:dexBuilderDebugAndroidTest UP-TO-DATE
> Task :libtmtu:mergeDebugAndroidTestGlobalSynthetics UP-TO-DATE
> Task :libtmtu:processDebugAndroidTestJavaRes UP-TO-DATE
> Task :libtmtu:mergeDebugAndroidTestJavaResource UP-TO-DATE
> Task :libtmtu:mergeProjectDexDebugAndroidTest UP-TO-DATE
> Task :libtmtu:packageDebugAndroidTest
> Task :libtmtu:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
Connected to process 655 on device 'newpos-new9220-0123456789ABCDEF'.

> Task :libtmtu:connectedDebugAndroidTest
Starting 0 tests on NEW9220 - 10

Finished 0 tests on NEW9220 - 10

> Task :libtmtu:connectedDebugAndroidTest FAILED
Test run failed to complete. Instrumentation run failed due to Process crashed.


Logcat of last crash: 


Process: com.tmtu.test, PID: 655

**java.lang.RuntimeException: Unable to get provider io.sentry.android.core.SentryInitProvider: java.lang.IllegalArgumentException: DSN is required. Use empty string or set enabled to false in SentryOptions to disable SDK.**


	at android.app.ActivityThread.installProvider(ActivityThread.java:7213)


	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6700)


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6613)


	at android.app.ActivityThread.access$1300(ActivityThread.java:234)


	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)


	at android.os.Handler.dispatchMessage(Handler.java:107)


	at android.os.Looper.loop(Looper.java:214)


	at android.app.ActivityThread.main(ActivityThread.java:7626)


	at java.lang.reflect.Method.invoke(Native Method)


	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)


	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)


Caused by: java.lang.IllegalArgumentException: DSN is required. Use empty string or set enabled to false in SentryOptions to disable SDK.


	at io.sentry.Sentry.initConfigurations(Sentry.java:378)


	at io.sentry.Sentry.init(Sentry.java:230)


	at io.sentry.Sentry.init(Sentry.java:167)


	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:90)


	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:61)


	at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:25)


	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)


	at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)


	at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:43)


	at android.app.ActivityThread.installProvider(ActivityThread.java:7208)


	... 10 more






FAILURE: 
Build failed with an exception.




* What went wrong:


Execution failed for task ':libtmtu:connectedDebugAndroidTest'.


> 
There were failing tests. See the report at: file:///Users/akhilhanda/Documents/projects/etim_app/libtmtu/build/reports/androidTests/connected/debug/index.html




* Try:


> 
Run with 
--stacktrace
 option to get the stack trace.


> 
Run with 
--info
 or 
--debug
 option to get more log output.


> 
Run with 
--scan
 to get full insights.


> 
Get more help at 
https://help.gradle.org
.
BUILD FAILED
 in 16s
123 actionable tasks: 7 executed, 116 up-to-date
`



Getting error while running tests in a multimodule app.
What I figured out is the DNS is added in the main application AndroidManifest, but we have another mode libtmtu which acts a module to implement Sentry as wrapper hence is dependent on Sentry library.
